var data = [
{"day":30,"count":1,"name":"Ahmad Mohammad Yassin al-Majayda","age":null,"place":" Khan Younis"},
{"day":30,"count":2,"name":"Ali Mahmoud al-Astal","age":23,"place":" Khan Younis"},
{"day":30,"count":3,"name":"Khaled Salim al-Astal","age":26,"place":" Khan Younis"},
{"day":30,"count":4,"name":"Mohammad Salim al-Astal","age":26,"place":" Khan Younis"},
{"day":30,"count":5,"name":"Ramzi Ibrahim al-Astal","age":21,"place":" Khan Younis"},
{"day":30,"count":6,"name":"Odah Ahmad al-Astal","age":25,"place":" Khan Younis"},
{"day":30,"count":7,"name":"Ahmad Mahmoud Suleiman al-Astal","age":26,"place":" Khan Younis"},
{"day":30,"count":8,"name":"Ahmad Ibrahim Ali al-Astal","age":null,"place":" Khan Younis"},
{"day":30,"count":9,"name":"Khalil Ibrahim Ali al-Astal","age":null,"place":" Khan Younis"},
{"day":30,"count":10,"name":"Ezzedddin Jabr Mohammad al-Astal","age":null,"place":" Khan Younis"},
{"day":30,"count":11,"name":"Mohammad Mahmoud al-Astal","age":null,"place":" Khan Younis"},
{"day":30,"count":12,"name":"Mohammad Abdul-Sattar al-Abadla","age":21,"place":" Khan Younis"},
{"day":30,"count":13,"name":"Fahd Mahmoud Jaber al-Agha","age":23,"place":" Khan Younis"},
{"day":30,"count":14,"name":"Asma’ Abu al-Kaas","age":16,"place":" al-Boreij Central Gaza"},
{"day":30,"count":15,"name":"Walid Shihda Marzouq Moammar","age":51,"place":" Rafah"},
{"day":30,"count":16,"name":"Sojoud Abdul-Hakim Oleyyan","age":11,"place":" Gaza"},
{"day":30,"count":17,"name":"Issam Jaber al-Khatib","age": null,"place":" Jabalia"},
{"day":30,"count":18,"name":"Sa’id Abu Jalala","age": null,"place":" Jabalia"},
{"day":30,"count":19,"name":"Taiseer Hammad","age": null,"place":" Jabalia"},
{"day":30,"count":20,"name":"Lu’ay al-Feery","age": null,"place":"Jabalia"},
{"day":30,"count":21,"name":"Bassem Khaled Najjar","age": null,"place":"Jabalia"},
{"day":30,"count":22,"name":"Tha’er Khaled Najjar","age": null,"place":"Jabalia"},
{"day":30,"count":23,"name":"Osama Mohammad Sohweil","age":null,"place":" Jabalia"},
{"day":30,"count":24,"name":"Bilal Midhat al-‘Amoudi","age":null,"place":" Jabalia"},
{"day":30,"count":25,"name":"Abdullah Midhat al-‘Amoudi","age":null,"place":" Jabalia"},
{"day":30,"count":26,"name":"Mohammad Mousa Ghaban","age":null,"place":" Jabalia"},
{"day":30,"count":27,"name":"Ramadan Khader Salman","age": null,"place":"Jabalia"},
{"day":30,"count":28,"name":"Alaa' Khader Salman","age":null,"place":" Jabalia"},
{"day":30,"count":29,"name":"Ali Ahmad Shaheen","age": null,"place":"Jabalia"},
{"day":30,"count":30,"name":"Rami Barakat","age":null,"place":" Jabalia"},
{"day":30,"count":31,"name":"Adel Mohammad Abu Qamar","age": null,"place":" Jabalia"},
{"day":30,"count":32,"name":"Mohammad Ezzat Abu Sweireh","age":34,"place":" Central District"},
{"day":30,"count":33,"name":"Hussein Mohammad Abu Rezeq","age":36,"place":" Rafah"},
{"day":30,"count":34,"name":"'Aed Zaqqout","age":null,"place":" Gaza City (coach of Palestine National Football Team)"},
{"day":30,"count":35,"name":"Abdul-Aziz Hosni Abu Hajras","age":23,"place":" Khan Younis"},
{"day":30,"count":36,"name":"Omar Awad al-Breem","age":null,"place":" Khan Younis"},
{"day":30,"count":37,"name":"Kamal Ahmad Al-Breem","age":57,"place":" Khan Younis"},
{"day":30,"count":38,"name":"Jihad Salah Mohammed al-Breem","age":28,"place":" Khan Younis"},
{"day":30,"count":39,"name":"Mariam Ahmad Hejazi","age":null,"place":" Khan Younis"},
{"day":30,"count":40,"name":"Salah Hejazi","age":null,"place":" Khan Younis"},
{"day":30,"count":41,"name":"Sabha Ibrahim Hejazi","age":null,"place":" Khan Younis"},
{"day":30,"count":42,"name":"Ibrahim Mousa al-Ghalban","age":null,"place":" Khan Younis"},
{"day":30,"count":43,"name":"Ismael Mahmoud al-Ghalban","age":null,"place":" Khan Younis"},
{"day":30,"count":44,"name":"Ahmad Suleiman Abu Amer","age":null,"place":" Khan Younis"},
{"day":30,"count":45,"name":"Mohammad Ahmad Abu Amer","age":null,"place":" Khan Younis"},
{"day":30,"count":46,"name":"Marwa Ahmad Abu Amer","age":null,"place":" Khan Younis"},
{"day":30,"count":47,"name":"Marah Ahmad Abu Amer","age":null,"place":" Khan Younis"},
{"day":30,"count":48,"name":"Yasser Ahmad Abu Amer","age":null,"place":" Khan Younis"},
{"day":30,"count":49,"name":"Suleiman Ahmad Abu Amer","age":null,"place":" Khan Younis"},
{"day":30,"count":50,"name":"Mona Hajjaj Abu Amer","age":null,"place":" Khan Younis"},
{"day":30,"count":51,"name":"Jihad Salah Mohammad Al-Breem","age":25,"place":" Khan Younis"},
{"day":30,"count":52,"name":"Zeinab Abu Jazar","age":null,"place":" Khan Younis"},
{"day":30,"count":53,"name":"Maisara Mohammad at-Ta’ban","age":35,"place":" Deir al-Balah"},
{"day":30,"count":54,"name":"Iftikhar Mohammad Shahin Abu Zrei’ey","age":50,"place":""},
{"day":30,"count":55,"name":"Odai Yahia Zaki Abu Jneid","age":19,"place":" Beit Lahia"},
{"day":30,"count":56,"name":"Abdul-Jalil Mohammad Kamel Abu Shodoq","age":35,"place":" Beit Lahia"},
{"day":30,"count":57,"name":"Jamal Shihda Abu Shodoq","age":40,"place":" Beit Lahia"},
{"day":30,"count":58,"name":"Jamalat Mahmoud Dheir","age":null,"place":" Khan Younis"},
{"day":30,"count":59,"name":"Salama Mahmoud Dheir","age":null,"place":" Khan Younis"},
{"day":30,"count":60,"name":"Mahmoud Salama Mahmoud Dheir","age":null,"place":" Khan Younis"},
{"day":30,"count":61,"name":"Yamen Omar Salama Mahmoud Dheir","age":null,"place":" Khan Younis"},
{"day":30,"count":62,"name":"Shorouq Mahmoud Dheir","age":null,"place":" Khan Younis"},
{"day":30,"count":63,"name":"Arwa Mahmoud Dheir","age":null,"place":" Khan Younis"},
{"day":30,"count":64,"name":"Ramadan Mohammad Abu Jazar","age":null,"place":" Khan Younis"},
{"day":30,"count":65,"name":"Ali Ahmad Shahin","age":null,"place":" Gaza"},
{"day":30,"count":66,"name":"Taiseer Sababa","age":22,"place":" Beit Lahia"},
{"day":30,"count":67,"name":"Ammar Suleiman Ali al-Masdar","age":31,"place":" Gaza"},
{"day":30,"count":68,"name":"Hamza Yasser Mohammad Mheisin","age":23,"place":" Gaza"},
{"day":30,"count":69,"name":"Wisam Dardouna","age":null,"place":" Beit Lahia"},
{"day":30,"count":70,"name":"Anwar ‘Adel Abu Nasr","age":20,"place":" Khan Younis"},
{"day":30,"count":71,"name":"Ismael Walid Abu Nasr","age":18,"place":" Khan Younis"},
{"day":30,"count":72,"name":"Ahmad Khalil Abu ‘Anza","age":32,"place":" Khan Younis"},
{"day":30,"count":73,"name":"Shadi Abdullah Abu ‘Anza","age":38,"place":" Khan Younis"},
{"day":30,"count":74,"name":"Ali Mahmoud Abu ‘Anza","age":27,"place":" Khan Younis"},
{"day":30,"count":75,"name":"Ahmad Abdullah Abu ‘Anza","age":null,"place":" Khan Younis"},
{"day":30,"count":76,"name":"Mohammad Suleiman Baraka","age":null,"place":" Khan Younis"},
{"day":30,"count":77,"name":"Mustafa Ahmad Abu Jalala","age":null,"place":" Beit Lahia"},
{"day":29,"count":1,"name":"Naji Ahmad al-Raqqab","age":19,"place":" Khan Younis"},
{"day":29,"count":2,"name":"Ramy Khaled al-Raqqab","age":35,"place":" Khan Younis"},
{"day":29,"count":3,"name":"Mahmoud Osama al-Qosas","age":null,"place":" Khan Younis"},
{"day":29,"count":4,"name":"Shadi Abd al-Kareem Farwana","age":null,"place":" Khan Younis"},
{"day":29,"count":5,"name":"Mustafa Abd al-Samiee al-Ubadala","age":null,"place":" Khan Younis"},
{"day":29,"count":6,"name":"Yahiya Mohammad Abdullah al-Aqqad","age":49,"place":" Khan Younis"},
{"day":29,"count":7,"name":"Yusef Emad Qaddoura","age":8,"place":" Jabalia"},
{"day":29,"count":8,"name":"Huna Emad Qaddoura","age":8,"place":" Jabalia"},
{"day":29,"count":9,"name":"Mohammad Musa Alwan","age":8,"place":" Jabalia"},
{"day":29,"count":10,"name":"Mariam Khalil Ruba","age":70,"place":" Jabalia"},
{"day":29,"count":11,"name":"Hani Abu Khalifa","age":null,"place":" Jabalia"},
{"day":29,"count":12,"name":"Soheila al-'Ejel","age":70,"place":" Gaza City"},
{"day":29,"count":13,"name":"Mo'nes Ahmad","age":null,"place":" Nusseirat"},
{"day":29,"count":14,"name":"Ezzat Dheir","age":23,"place":" Rafah"},
{"day":29,"count":15,"name":"Turkeyya Dheir","age":80,"place":" Rafah"},
{"day":29,"count":16,"name":"Yasmeen Dheir","age":25,"place":" Rafah"},
{"day":29,"count":17,"name":"Mary Dheir","age":12,"place":" Rafah"},
{"day":29,"count":18,"name":"Tasneem Dheir","age":8,"place":" Rafah"},
{"day":29,"count":19,"name":"Soheil Hasan Nassar","age":null,"place":" Beit Lahia"},
{"day":29,"count":20,"name":"Anis Abu Shammala","age":null,"place":" Al-Boreij (Mayor)"},
{"day":29,"count":21,"name":"Ayman Samir Qeshta","age":30,"place":" Rafah"},
{"day":29,"count":22,"name":"Ismael Shahin","age":27,"place":" Rafah"},
{"day":29,"count":23,"name":"Baha’ ed-Deen al-Gharib","age":null,"place":" Rafah"},
{"day":29,"count":24,"name":"Ola Baha’ ed-Deen al-Gharib","age":null,"place":" Rafah"},
{"day":29,"count":25,"name":"Tahrir Nasr Jaber","age":15,"place":" Northern Gaza"},
{"day":29,"count":26,"name":"Mohammad Ata Najjar","age":2,"place":" Khan Younis"},
{"day":29,"count":27,"name":"Rafif Ata Najjar","age":3,"place":" Khan Younis"},
{"day":29,"count":28,"name":"Baha' ed-Deen Khatib","age":30,"place":" Rafah"},
{"day":29,"count":29,"name":"'Ola Baha' ed-Deen Khatib","age":null,"place":" Rafah"},
{"day":29,"count":30,"name":"Waddah Abu Amer","age":null,"place":" Khan Younis"},
{"day":29,"count":31,"name":"Ahmad Suleiman Ahmad Abu Amer","age":null,"place":" Khan Younis"},
{"day":29,"count":32,"name":"Mohammed Ahmad Abu Amer","age":null,"place":" Khan Younis"},
{"day":29,"count":33,"name":"Marwa Ahmad Abu Amer ","age":null,"place":" Khan Younis"},
{"day":29,"count":34,"name":"Marah Ahmad Abu Amer ","age":null,"place":" Khan Younis"},
{"day":29,"count":35,"name":"Yasser Ahmad Abu Amer ","age":null,"place":" Khan Younis"},
{"day":29,"count":36,"name":"Suleiman Ahmad Abu Amer","age":null,"place":" Khan Younis"},
{"day":29,"count":37,"name":"Moha Hajjaj Abu Amer ","age":null,"place":" Khan Younis"},
{"day":29,"count":38,"name":"Mos'ab Ahmad Sweih","age":17,"place":" Gaza"},
{"day":29,"count":39,"name":"Nariman Khalil al-Agha","age":39,"place":" Gaza"},
{"day":29,"count":40,"name":"Ali Mohammad Abu Ma'rouf","age":23,"place":" Gaza"},
{"day":29,"count":41,"name":"Dr Bashir al-Hajjar","age":null,"place":" northern Gaza"},
{"day":29,"count":42,"name":"Samir al-Hajjar","age":null,"place":" northern Gaza"},
{"day":29,"count":43,"name":"Hana’ Na’im Balata","age":null,"place":" Jabalia"},
{"day":29,"count":44,"name":"Doa’ Na’im Balata","age":null,"place":" Jabalia"},
{"day":29,"count":45,"name":"Esra’ Na’im Balata","age":null,"place":" Jabalia"},
{"day":29,"count":46,"name":"Mariam Na’im Balata","age":null,"place":" Jabalia"},
{"day":29,"count":47,"name":"Yahia Na’im Balata","age":null,"place":" Jabalia"},
{"day":29,"count":48,"name":"Sahar Motawe’ Balata","age":null,"place":" Jabalia"},
{"day":29,"count":49,"name":"Naim Nathmi","age":null,"place":" Jabalia"},
{"day":29,"count":50,"name":"Zaher Ahmad Najjar","age":6,"place":" Khan Younis"},
{"day":29,"count":51,"name":"Suleiman Mos'ad Barham al-Hishash","age":30,"place":" Rafah"},
{"day":29,"count":52,"name":"Jamal Ramadan Lafi","age":50,"place":" Rafah"},
{"day":29,"count":53,"name":"Karam Abu Zeid","age":1,"place":""},
{"day":28,"count":1,"name":"Samih Jebriel Jneid","age":4,"place":" Jabalia"},
{"day":28,"count":2,"name":"Mohammad Abu Louz","age":22,"place":" Jabalia"},
{"day":28,"count":3,"name":"Ahmad Abdullah Hasan Abu Zeid","age":null,"place":" Rafah"},
{"day":28,"count":4,"name":"Widad Ahmad Salama Abu Zeid","age":null,"place":" Rafah"},
{"day":28,"count":5,"name":"Sham'a Wael Abu Zeid","age":null,"place":" Rafah"},
{"day":28,"count":6,"name":"Mariam Marzouq Abu Zeid","age":null,"place":" Rafah"},
{"day":28,"count":7,"name":"Falasteen Mohammad Abu Zeid","age":null,"place":" Rafah"},
{"day":28,"count":8,"name":"Abdullah Nidal Abu Zeid","age":9,"place":" Rafah"},
{"day":28,"count":9,"name":"Bissan Eyad Abu Zeid","age":null,"place":" Rafah"},
{"day":28,"count":10,"name":"Abdul-Hadi Abu Zeid","age":9,"place":" Rafah"},
{"day":28,"count":11,"name":"Seham Najjar","age":42,"place":" Khan Younis"},
{"day":28,"count":12,"name":"Abdul-Samad Mahmoud Ahmad Ramadan","age":16,"place":" Central District"},
{"day":28,"count":13,"name":"Ayman Adnan Mousa Shaker","age":25,"place":" Central District"},
{"day":28,"count":14,"name":"Issa Kamel Abdul-Rahman Mousa","age":61,"place":" Central District"},
{"day":28,"count":15,"name":"Salem Mousa Badawi al-Far","age":59,"place":" Central District"},
{"day":28,"count":16,"name":"Ramzi Hussein Ahmad al-Far","age":null,"place":" Central District"},
{"day":28,"count":17,"name":"Salem Mohammad al-Far","age":null,"place":" Central District"},
{"day":28,"count":18,"name":"Azza Abdul-Karim Abdul-Rahman Al-Faleet","age":59,"place":" Central District"},
{"day":28,"count":19,"name":"Mohammad Jom’a Shaat","age":30,"place":" Khan Younis"},
{"day":28,"count":20,"name":"Mohammad Fadel al-‘Agha","age":30,"place":" Khan Younis"},
{"day":28,"count":21,"name":"Marwa Nader al-Agha","age":null,"place":" Khan Younis"},
{"day":28,"count":22,"name":"Ahmad Nader Al-Agha","age":null,"place":" Khan Younis"},
{"day":28,"count":23,"name":"Donia Nader al-Agha","age":13,"place":" Khan Younis"},
{"day":27,"count":1,"name":"Ikram ash-Shinbari","age":23,"place":" Gaza City"},
{"day":27,"count":2,"name":"Yusef Jamil Sobhi Hammouda","age":16,"place":" Gaza City"},
{"day":27,"count":3,"name":"Ibrahim Khalil ad-Derawi","age":27,"place":" central District"},
{"day":27,"count":4,"name":"Ala Nahedh Matar","age":26,"place":" central District"},
{"day":27,"count":5,"name":"Hazem Fayez Abu Shammala","age":33,"place":" central District"},
{"day":27,"count":6,"name":"Issam Abdul-Karim Abu Sa’ada","age":null,"place":" Khan Younis"},
{"day":27,"count":7,"name":"Ahmad Abu Sweirej","age":23,"place":" Nusseirat"},
{"day":27,"count":8,"name":"Mohammad Abu Haroun","age":29,"place":" Nusseirat"},
{"day":27,"count":9,"name":"Fadi Baraka","age":10,"place":"Gaza"},
{"day":27,"count":10,"name":"Baha’ ed-Deen Ahmad Sa’id","age":null,"place":" al-Maghazi"},
{"day":27,"count":11,"name":"Yousef Abed Shehada al-Masri","age":24,"place":" Shuja'eyya"},
{"day":27,"count":12,"name":"Khaled Abdul-Sattar Samhoud","age":null,"place":" Khan Younis"},
{"day":27,"count":13,"name":"Jalila Faraj Ayyad","age":null,"place":" Gaza City"},
{"day":27,"count":14,"name":"Essam Ibrahim Abu Shab 42","age":null,"place":""},
{"day":27,"count":15,"name":"Mohammad Siyam","age":15,"place":" Rafah"},
{"day":27,"count":16,"name":"Hussein Hasan Abu an-Naja","age":65,"place":" Khan Younis"},
{"day":27,"count":17,"name":"Imad Jami al-Abed al-Bardaweel","age":44,"place":" Gaza"},
{"day":26,"count":1,"name":"Husam Abul-Ghani Yassin","age":15,"place":" Gaza"},
{"day":26,"count":2,"name":"Ismael Abdul-Qader al-Kojok","age":53,"place":" Gaza"},
{"day":26,"count":3,"name":"Mohammad Hosni as-Saqqa","age":20,"place":" Gaza"},
{"day":26,"count":4,"name":"Islam Ibrahim an-Naji","age":19,"place":"Gaza"},
{"day":26,"count":5,"name":"Mohammad Matar a-Abadla","age":32,"place":" Gaza"},
{"day":26,"count":6,"name":"Yorsa Salem Hasan al-Breem","age":65,"place":" Gaza"},
{"day":26,"count":7,"name":"Mohammad Ahmad Abu Wadia","age":19,"place":" Gaza"},
{"day":26,"count":8,"name":"Hani Adel Abu Hassanen","age":24,"place":" Gaza"},
{"day":26,"count":9,"name":"Abdullah ‘Ayesh Salam Ermeilat","age":39,"place":" Deir al-Balah"},
{"day":26,"count":10,"name":"Eman Hasan ar-Raqeeb","age":null,"place":"Khan Younis"},
{"day":26,"count":11,"name":"Bara' Mahmoud ar-Raqeeb","age":11,"place":""},
{"day":26,"count":12,"name":"Khalil al-Najjar","age":59,"place":" Khan Younis"},
{"day":26,"count":13,"name":"Jona al-Najjar","age":null,"place":"Khan Younis"},
{"day":26,"count":14,"name":"Ekhlas Najjar","age":null,"place":"Khan Younis"},
{"day":26,"count":15,"name":"Amna al-Najjar","age":null,"place":"Khan Younis"},
{"day":26,"count":16,"name":"Mutaz al-Najjar","age":null,"place":"Khan Younis"},
{"day":26,"count":17,"name":"Majed Sameer Al-Najjar","age":19,"place":" Khan Younis"},
{"day":26,"count":18,"name":"Ghalia Mohammed al-Najjar","age":56,"place":" Khan Younis"},
{"day":26,"count":19,"name":"Ahmad Khaled al-Najjar","age":14,"place":" Khan Younis"},
{"day":26,"count":20,"name":"Eman Salah al-Najjar","age":20,"place":" Khan Younis"},
{"day":26,"count":21,"name":"Ulfat Hussein al-Najjar","age":4,"place":" Khan Younis"},
{"day":26,"count":22,"name":"Sumayya Harb al-Najjar","age":50,"place":" Khan Younis"},
{"day":26,"count":23,"name":"Kifah Samir al-Najjar","age":23,"place":" Khan Younis"},
{"day":26,"count":24,"name":"Rawan Khaled al-Najjar","age":17,"place":" Khan Younis"},
{"day":26,"count":25,"name":"Husam Hussein al-Najjar","age":7,"place":" Khan Younis"},
{"day":26,"count":26,"name":"Samir Hussein al-Najjar","age":2,"place":" Khan Younis"},
{"day":26,"count":27,"name":"Ikhlas Sameer Abu Shahla","age":30,"place":" Khan Younis"},
{"day":26,"count":28,"name":"Amira Hammoudeh Abu Shahla","age":1,"place":" Khan Younis"},
{"day":26,"count":29,"name":"Islam Hammoudeh Abu Shahla","age":4,"place":" Khan Younis"},
{"day":26,"count":30,"name":"Riham Fayez al-Breem","age":19,"place":""},
{"day":26,"count":31,"name":"Fadel At-Tawaneh","age":null,"place":"Gaza City"},
{"day":26,"count":32,"name":"Arafat Abu Oweily","age":null,"place":" Central District"},
{"day":26,"count":33,"name":"Abdul-Rahman Ouda at-Tilbani","age":null,"place":"Central District"},
{"day":26,"count":34,"name":"Nidal Ahmad 'Issa Abu al-'Asal","age":27,"place":" Rafah"},
{"day":26,"count":35,"name":"Salim Salaam Abu ath-Thoum","age":87,"place":" Rafah"},
{"day":25,"count":1,"name":"Maram Rajeh Fayyad","age":26,"place":" Deir al-Balah"},
{"day":25,"count":2,"name":"Shaima’ Hussein Abdul-Qadder Qannan pregnant","age":23,"place":" Gaza"},
{"day":25,"count":3,"name":"Abdul-Hadi Salah Abu Hasanen","age":9,"place":" Rafah"},
{"day":25,"count":4,"name":"Hadi Salah ed-Deen Abu Hassanen","age":12,"place":"Rafah"},
{"day":25,"count":5,"name":"Salah Ahmad Hassanen","age":45,"place":" Rafah"},
{"day":25,"count":6,"name":"Abdul-Aziz Salah Ahmad Hassanen","age":15,"place":" Rafah"},
{"day":25,"count":7,"name":"Abdul-Hadi Salam Ahmad Hassanen","age":9,"place":"Rafah"},
{"day":25,"count":8,"name":"Mohammad Ibrahim al-Khatib","age":27,"place":" Khan Younis"},
{"day":25,"count":9,"name":"Mohammad Samir Najjar","age":25,"place":" Khan Younis"},
{"day":25,"count":10,"name":"Rasmiyya Salama","age":24,"place":" Khan Younis"},
{"day":25,"count":11,"name":"Suleiman ash-Shawwaf","age":21,"place":" Khan Younis"},
{"day":25,"count":12,"name":"Rasha Abed-Rabbo ‘Affana","age":25,"place":" northern Gaza"},
{"day":25,"count":13,"name":"Ali Mohammad Asfour","age":58,"place":" Khan Younis"},
{"day":25,"count":14,"name":"Eid Mohammad Abu Qteifan","age":23,"place":" Deir al-Balah"},
{"day":25,"count":15,"name":"Eyad Nassr Sharab","age":null,"place":"Khan Younis"},
{"day":25,"count":16,"name":"Najat Ibrahim an-Najjar","age":35,"place":" Khan Younis"},
{"day":25,"count":17,"name":"Sharif Mohammad Hasan","age":27,"place":" Khan Younis"},
{"day":25,"count":18,"name":"Mohammad Khalil Hamad","age":18,"place":" Khan Younis"},
{"day":25,"count":19,"name":"Mandouh Ibrahim ash-Shawaf","age":25,"place":" Khan Younis"},
{"day":25,"count":20,"name":"Walid Sa’id al-Harazin","age":5,"place":" Gaza"},
{"day":25,"count":21,"name":"Tareq Zohdi","age":22,"place":" Meghraqa"},
{"day":25,"count":22,"name":"Salama Abu Kamil","age":26,"place":" Central District"},
{"day":25,"count":23,"name":"Ahmad Mahdi Abi Zour","age":25,"place":" Gaza"},
{"day":25,"count":24,"name":"Naji Bassem Abu Ammouna","age":25,"place":" Gaza"},
{"day":25,"count":25,"name":"Imad Adnan Abu Kamil","age":20,"place":" Al-Meghraqa"},
{"day":25,"count":26,"name":"Mohammad Yassin Siyam","age":null,"place":"Zeitoun - Gaza"},
{"day":25,"count":27,"name":"Rami Mohammad Yassin","age":null,"place":"Zeitoun"},
{"day":25,"count":28,"name":"Osama Salim Shaheen","age":27,"place":" Khan Younis"},
{"day":25,"count":29,"name":"Hamada Suleiman Abu Younis","age":25,"place":""},
{"day":25,"count":30,"name":"Mohammad Kamel an-Naqa","age":34,"place":" Khan Younis"},
{"day":25,"count":31,"name":"Kamaal Kamel an-Naqa","age":35,"place":" Khan Younis"},
{"day":25,"count":32,"name":"Yousef Kamal Mohammed al-Wasify","age":26,"place":" Gaza City"},
{"day":25,"count":33,"name":"Mazin Abdeen","age":23,"place":" Rafah"},
{"day":25,"count":34,"name":"Adnan Shahid Ashteiwi Abdeen","age":35,"place":" Rafah"},
{"day":25,"count":35,"name":"Mohammad Abdel Nasser Abu Zina","age":24,"place":" al-Zaitoun"},
{"day":25,"count":36,"name":"Abdul Majeed al-Eidi","age":35,"place":" al-Zaitoun"},
{"day":25,"count":37,"name":"Mohammad Ahmed Abu Wadiya","age":19,"place":" Gaza City"},
{"day":25,"count":38,"name":"Hani 'Adel Abu Hassanein","age":24,"place":" Gaza City"},
{"day":25,"count":39,"name":"Yassin Mustafa al-Astal","age":38,"place":" Khan Younis"},
{"day":25,"count":40,"name":"Yosra Salem Hasan al-Breem","age":65,"place":" Khan Younis"},
{"day":25,"count":41,"name":"Mohammad Issa Khaled Hajji","age":24,"place":" Gaza City"},
{"day":25,"count":42,"name":"Hasan Hussein al-Howwari","age":null,"place":" Gaza City"},
{"day":25,"count":43,"name":"Hosam Rabhi","age":null,"place":"Gaza City"},
{"day":25,"count":44,"name":"Hamed al-Bora'ey","age":null,"place":" Beit Hanoun"},
{"day":25,"count":45,"name":"Mohammad Matar al-'Abadla","age":32,"place":" Khan Younis"},
{"day":24,"count":1,"name":"Bassam Khaled Abu Shahla","age":44,"place":" Khan Younis"},
{"day":24,"count":2,"name":"Ahmad Rif’at Ar-Roqab","age":23,"place":" Khan Younis"},
{"day":24,"count":3,"name":"Salman Salman al-Breem","age":27,"place":" Khan Younis"},
{"day":24,"count":4,"name":"Mohammad Hasan Abdul-Qader al-Astal","age":43,"place":" Khan Younis"},
{"day":24,"count":5,"name":"Mohammad Ismael al-Astal","age":17,"place":" Khan Younis"},
{"day":24,"count":6,"name":"Ismael Mohammad al-Astal","age":48,"place":" Khan Younis"},
{"day":24,"count":7,"name":"Ahmad Mohammad Ismael al-Astal","age":20,"place":" Khan Younis"},
{"day":24,"count":8,"name":"Mohammad Saleh Mohammad al-Astal","age":18,"place":""},
{"day":24,"count":9,"name":"Malak Amin Ahmad al-Astal","age":24,"place":" Khan Younis"},
{"day":24,"count":10,"name":"Tha’er Omran Khamis al-Astal","age":30,"place":""},
{"day":24,"count":11,"name":"Milad Omran al-Astal","age":29,"place":" Khan Younis"},
{"day":24,"count":12,"name":"Mohammad Omran Khamis al-Astal","age":33,"place":" Khan Younis"},
{"day":24,"count":13,"name":"Ahmad Thaer Omran al-Astal","age":33,"place":" Khan Younis"},
{"day":24,"count":14,"name":"Amin Thaer Omran al-Astal","age":3,"place":"Khan Younis"},
{"day":24,"count":15,"name":"Nada Thaer Omran al-Astal","age":5,"place":" Khan Younis"},
{"day":24,"count":16,"name":"Yazid Sa’ad al-Batsh","age":23,"place":" Gaza"},
{"day":24,"count":17,"name":"Ibrahim Abdullah Abu Aita","age":67,"place":" Jabalia"},
{"day":24,"count":18,"name":"Ahmad Ibrahim Abdullah Abu Aita","age":30,"place":" Jabalia"},
{"day":24,"count":19,"name":"Jamila Salim Abu Aita","age":65,"place":" Jabalia"},
{"day":24,"count":20,"name":"Adham Ahmad Abu Aita","age":11,"place":" Jabalia"},
{"day":24,"count":21,"name":"Khalil Nasser Aita Wishah","age":21,"place":" Central District"},
{"day":24,"count":22,"name":"Mohammad Ibrahim Abu Aita","age":32,"place":" Jabalia"},
{"day":24,"count":23,"name":"Ahmad Ibrahim Said al-Qar’an","age":26,"place":" Central District"},
{"day":24,"count":24,"name":"Hadi Abdul-Hamid Abdul Nabi","age":2,"place":" Jabalia"},
{"day":24,"count":25,"name":"Yahia Ibrahim Abu 'Arbaid","age":null,"place":" Beit Hanoun"},
{"day":24,"count":26,"name":"Mohammad Suleiman an-Najjar","age":null,"place":" Khuza'a Khan Younis"},
{"day":24,"count":27,"name":"Bilal Zayad 'Alwan","age":20,"place":" Jabalia"},
{"day":24,"count":28,"name":"Majed Mohammad","age":26,"place":" Jabalia"},
{"day":24,"count":29,"name":"Mohammed Ibrahim Abu Daqqa","age":42,"place":" Khan Younis"},
{"day":24,"count":30,"name":"Akram Ibrahim Abu Daqqa","age":50,"place":" Khan Younis"},
{"day":24,"count":31,"name":"Salameh al-Rade'a","age":1,"place":" northern Gaza"},
{"day":24,"count":32,"name":"Ismail Hussein Abu Rjeila","age":null,"place":"Khan Younis"},
{"day":24,"count":33,"name":"Nafez Suleiman Qdeih","age":35,"place":" Khan Younis"},
{"day":24,"count":34,"name":"Nabil Shehda Qdeih","age":45,"place":" Khan Younis"},
{"day":24,"count":35,"name":"Baker an-Najjar","age":13,"place":" Khan Younis"},
{"day":24,"count":36,"name":"Mohammad Ahmad Najjar","age":null,"place":"Khan Younis"},
{"day":24,"count":37,"name":"Anwar Ahmad Najjar","age":null,"place":"Khan Younis"},
{"day":24,"count":38,"name":"Anwar Ahmad Abu Daqqa","age":null,"place":"Khan Younis"},
{"day":24,"count":39,"name":"Mousa Abu Daqqa","age":null,"place":"Khan Younis"},
{"day":24,"count":40,"name":"Adli Khalil Abu Daqqa","age":null,"place":" Khan Younis"},
{"day":24,"count":41,"name":"Ahmad Abdul-Karim Ahmad Hasan","age":null,"place":" Khan Younis"},
{"day":24,"count":42,"name":"‘Ola Abu Aida","age":27,"place":" Zahra - Khan Younis"},
{"day":24,"count":43,"name":"Ahmad Abdul-Karim Hasan","age":null,"place":" Zahra – Khan Younis"},
{"day":24,"count":44,"name":"Mohammad Ismael Khader","age":null,"place":" Zahra – Khan Younis"},
{"day":24,"count":45,"name":"Anas Akram Skafi","age":18,"place":" Shujaeyya - Gaza"},
{"day":24,"count":46,"name":"Sa’ad Akram Skafi","age":18,"place":" Shujaeyya - Gaza"},
{"day":24,"count":47,"name":"Mohammad Jihad Matar","age":null,"place":" Beit Hanoun"},
{"day":24,"count":48,"name":"Amna Jihad Matar","age":null,"place":" Beit Hanoun"},
{"day":24,"count":49,"name":"Tamam Mohammad Hamad","age": null ,"place":" Beit Hanoun"},
{"day":24,"count":50,"name":"Khader Khalil al-Louh","age":50,"place":" Atatra Northern Gaza"},
{"day":24,"count":51,"name":"Ramsi Mousa Abu Reeda","age":null,"place":" Khan Younis"},
{"day":24,"count":52,"name":"Mohammad Abu Yousef","age":null,"place":" Khan Younis"},
{"day":24,"count":53,"name":"Ahmad Qdeih","age":null,"place":" Khan Younis"},
{"day":24,"count":54,"name":"Rami Qdeih","age":null,"place":" Khan Younis"},
{"day":24,"count":55,"name":"Khader Khalil al-Louh","age":50,"place":" Northern Gaza"},
{"day":24,"count":56,"name":"Badr Hatem Qdeih","age":13,"place":" Khuza’a Khan Younis"},
{"day":24,"count":57,"name":"Hanafi Mahmoud Abu Yousef","age":42,"place":" Khuza’a Khan Younis"},
{"day":24,"count":58,"name":"Abdel Aziz Nour El Din Noor","age":21,"place":" Shuja’eyya"},
{"day":24,"count":59,"name":"Amir Islam Adel","age":9,"place":" Rafah"},
{"day":24,"count":60,"name":"Amir Adel Siam Siam 13","age":null,"place":" Rafah"},
{"day":24,"count":61,"name":"Issam Faisal Siam","age":23,"place":" Rafah"},
{"day":24,"count":62,"name":"Mahmoud Silmy Rowaished","age":50,"place":" Rafah"},
{"day":24,"count":63,"name":"Ahmed Abu Jm'ean Hji'er 19","age":null,"place":" Al-Bureij"},
{"day":24,"count":64,"name":"Amer Abdul-Raouf Mohamed El Azab","age":26,"place":" Deir al-Balah"},
{"day":24,"count":65,"name":"Tha'er Owda Shamaly","age":19,"place":" Shuja’eyya"},
{"day":24,"count":66,"name":"Mohammed Yousef Al-Qadi","age":27,"place":" had been in Egyptian hospital"},
{"day":24,"count":67,"name":"Yasmin Ahmed Abu Moor","age":27,"place":" had been in Egyptian hospital"},
{"day":24,"count":68,"name":"Mohammed Rateb Abu Jazr","age":26,"place":" Khan Younis"},
{"day":24,"count":69,"name":"Hisham Mohammad Abu Jazr","age":23,"place":" Khan Younis"},
{"day":24,"count":70,"name":"Mohammed Farhan Abu Jazr","age":19,"place":" Khan Younis"},
{"day":24,"count":71,"name":"Shadi Suleiman Kawar'e","age":31,"place":" Khan Younis"},
{"day":24,"count":72,"name":"Ra'ed Abu Owda","age":17,"place":" Beit Hanoun"},
{"day":24,"count":73,"name":"Ashraf Ibrahim Hasan Najjar","age":13,"place":" Khan Younis"},
{"day":24,"count":74,"name":"Mahmoud Jihad Awad Abdin","age":12,"place":" Khan Younis"},
{"day":24,"count":75,"name":"Ahmad Talal Najjar","age":null,"place":"Khan Younis"},
{"day":24,"count":76,"name":"Mohammad Abdullah Najjar","age":null,"place":"Khan Younis"},
{"day":24,"count":77,"name":"Sana’ Hasan Ali al-Astal","age":null,"place":" Khan Younis"},
{"day":24,"count":78,"name":"Nabil Mahmoud Mohammad al-Astal","age":12,"place":" Khan Younis"},
{"day":24,"count":79,"name":"Ashraf Mahmoud Mohammad al-Astal","age":null,"place":" Khan Younis"},
{"day":24,"count":80,"name":"Mahmoud Suleiman al-Astal","age":17,"place":" Khan Younis"},
{"day":24,"count":81,"name":"Laila Ibrahim Zo’rob","age":40,"place":" Rafah"},
{"day":24,"count":82,"name":"Mahmoud As’ad Ghaban","age":24,"place":" Beit Lahia"},
{"day":24,"count":83,"name":"Ibrahim Jihad Abu Laban","age":27,"place":" Zeitoun - Gaza"},
{"day":24,"count":84,"name":"Mahmoud Jihad Awad Abdin","age":12,"place":" Khan Younis"},
{"day":24,"count":85,"name":"Ibrahim Sheikh Omar","age":3,"place":" Gaza"},
{"day":23,"count":1,"name":"Hasan Abu Hayyin","age":70,"place":" Shujaeyya"},
{"day":23,"count":2,"name":"Abdul-Rahman Abu Hayyin","age":24,"place":" "},
{"day":23,"count":3,"name":"Osama Bahjat Rajab","age":34,"place":" Beit Lahia"},
{"day":23,"count":4,"name":"Mohammad Daoud Hammouda","age":33,"place":" Beit Lahia"},
{"day":23,"count":5,"name":"Hamza Ziyada Abu ‘Anza","age":18,"place":" Khan Younis"},
{"day":23,"count":6,"name":"Saddam Ibrahim Abu Assi","age":23,"place":" Khan Younis"},
{"day":23,"count":7,"name":"Wisam ‘Ala Najjar","age":17,"place":" Khan Younis"},
{"day":23,"count":8,"name":"Mohammad Mansour al-Bashiti","age":7,"place":" Khan Younis"},
{"day":23,"count":9,"name":"Bassam Abdullah Abu T’eimi","age":23,"place":" Khan Younis"},
{"day":23,"count":10,"name":"Mohammad Na’im Abu T’eimi","age":25,"place":" Khan Younis"},
{"day":23,"count":11,"name":"Ismail Abu Tharifa","age":null,"place":" Khan Younis"},
{"day":23,"count":12,"name":"Zeinab Abu Teir","age":8,"place":" Khan Younis"},
{"day":23,"count":13,"name":"Mohammad Radi Abu Redya","age":22,"place":" Khan Younis"},
{"day":23,"count":14,"name":"Shama Shahin","age":null,"place":" Khan Younis"},
{"day":23,"count":15,"name":"Mojahed Marwan Skafi","age":20,"place":" Shujaeyya"},
{"day":23,"count":16,"name":"Adnan Ghazi Habib","age":23,"place":" central Gaza"},
{"day":23,"count":17,"name":"Ibrahim Ahmad Shbeir","age":24,"place":" Khan Younis"},
{"day":23,"count":18,"name":"Mustafa Mohammad Mahmoud Fayyad","age":24,"place":" northern Gaza"},
{"day":23,"count":19,"name":"Nidal Hamad al-‘Ejla","age":25,"place":" Gaza"},
{"day":23,"count":20,"name":"Khalil Abu Jame’","age":null,"place":" Khan Younis"},
{"day":23,"count":21,"name":"Husam al-Qarra","age":null,"place":" Khan Younis"},
{"day":23,"count":22,"name":"Rabea’ Qassem","age":12,"place":" Northern Gaza"},
{"day":23,"count":23,"name":"Hasan Salah Abu Jamous","age":29,"place":" Khan Younis"},
{"day":23,"count":24,"name":"Mahmoud Yousef Khaled al-‘Abadla","age":22,"place":" Khan Younis"},
{"day":23,"count":25,"name":"Nour Abdul-Rahim al-‘Abadla","age":22,"place":" Khan Younis"},
{"day":23,"count":26,"name":"Mohammad Farid al-Astal","age":null,"place":" Khan Younis"},
{"day":23,"count":27,"name":"Mohammad Abdul-Ra’ouf ad-Dadda","age":39,"place":" Gaza"},
{"day":23,"count":28,"name":"Ahmad Mohammad Bolbol","age":null,"place":" Gaza"},
{"day":23,"count":29,"name":"Ibrahim Omar al-Hallaq","age":40,"place":" Khan Younis"},
{"day":23,"count":30,"name":"Wael Maher Awwad","age":23,"place":" Khan Younis"},
{"day":23,"count":31,"name":"Ahmad Mahmoud Sohweil","age":23,"place":" Khan Younis"},
{"day":23,"count":32,"name":"Issam Ismael Abu Shaqra","age":42,"place":" Khan Younis"},
{"day":23,"count":33,"name":"Abdul-Rahman Ibrahim Abu Shaqra","age":17,"place":" Khan Younis"},
{"day":23,"count":34,"name":"Mohammad Ahmad Akram Abu Shaqra","age":17,"place":" Khan Younis"},
{"day":23,"count":35,"name":"Ahmad as-Saqqa","age":17,"place":" Khan Younis"},
{"day":23,"count":36,"name":"Fayez Nayeth ath-Thatha","age":24,"place":" Zeitoun – Gaza"},
{"day":23,"count":37,"name":"Fayez Na’im ath-Thatha","age":17,"place":" Zeitoun – Gaza"},
{"day":23,"count":38,"name":"‘Ala Jihad Ali Khattab","age":25,"place":" Deir al-Balah"},
{"day":23,"count":39,"name":"Abdul-Qader Jamil al-Khalidi","age":23,"place":" al-Boreij"},
{"day":23,"count":40,"name":"Ayman Adham Yousef Ahmad","age":16,"place":" Beit Lahia"},
{"day":23,"count":41,"name":"Bilal Ali Ahmad Abu ‘Adra","age":25,"place":" Beit Lahia"},
{"day":23,"count":42,"name":"Abdul-Karim Saleh Abu Jarmi","age":24,"place":" Beit Lahia"},
{"day":22,"count":1,"name":"Naji Jamal al-Fajm","age":26,"place":" Khan Younis"},
{"day":22,"count":2,"name":"Ebtehal Ibrahim ar-Remahi","age":null,"place":"Deir al-Balah"},
{"day":22,"count":3,"name":"Yousef Ibrahim ar-Remahi","age":null,"place":"Deir al-Balah"},
{"day":22,"count":4,"name":"Eman Ibrahim ar-Remahi","age":null,"place":"Deir al-Balah"},
{"day":22,"count":5,"name":"Salwa Abu Mneifi","age":null,"place":"Khan Younis"},
{"day":22,"count":6,"name":"Salwa Abu Mneifi","age":null,"place":"Khan Younis"},
{"day":22,"count":7,"name":"Abdullah Ismael al-Baheessy","age":27,"place":" Deir al-Balah"},
{"day":22,"count":8,"name":"Mos’ab Saleh Salama","age":19,"place":" Khan Younis"},
{"day":22,"count":9,"name":"Ibrahim Nasr Haroun","age":38,"place":" Nusseirat"},
{"day":22,"count":10,"name":"Mahmoud Suleiman Abu Sabha","age":55,"place":" Khan Younis"},
{"day":22,"count":11,"name":"Hasan Khader Baker","age":60,"place":" Gaza City"},
{"day":22,"count":12,"name":"Wa’el Jamal Harb","age":32,"place":" Rafah"},
{"day":22,"count":13,"name":"Suleiman Abu Daher","age":21,"place":" Khan Younis"},
{"day":22,"count":14,"name":"Haitham Samir al-Agha","age":26,"place":" Khan Younis"},
{"day":22,"count":15,"name":"Fatima Hasan Azzam","age":70,"place":" Gaza"},
{"day":22,"count":16,"name":"Mariam Hasan Azzam","age":50,"place":" Gaza"},
{"day":22,"count":17,"name":"Yasmeen Ahmad Abu Mour","age":2,"place":" Rafah"},
{"day":22,"count":18,"name":"Samer Zuheri Sawafiri","age":29,"place":" Rafah"},
{"day":22,"count":19,"name":"Mohammad Mousa Fayyad","age":36,"place":" Khan Younis"},
{"day":22,"count":20,"name":"Mona Rami al-Kharwat","age":4,"place":" Gaza"},
{"day":22,"count":21,"name":"Soha Na’im al-Kharwat","age":25,"place":" Gaza"},
{"day":22,"count":22,"name":"Ahmad Salah Abu Siedo","age":17,"place":" Gaza"},
{"day":22,"count":23,"name":"Mohammad Khalil Ahl","age":65,"place":" Gaza"},
{"day":22,"count":24,"name":"Mahmoud Salim Daraj","age":22,"place":" Jabalia"},
{"day":22,"count":25,"name":"Radhi Abu Hweishel","age":40,"place":" Nusseirat"},
{"day":22,"count":26,"name":"Obeida Abu Hweishel","age":15,"place":" Nusseirat"},
{"day":22,"count":27,"name":"Yousef Abu Mustafa","age":27,"place":" Nusseirat"},
{"day":22,"count":28,"name":"Nour al-Islam Abu Hweishel","age":12,"place":" Nusseirat"},
{"day":22,"count":29,"name":"Yousef Fawza Abu Mustafa","age":20,"place":" Nusseirat"},
{"day":22,"count":30,"name":"Hani Awad Sammour","age":27,"place":" Khan Younis"},
{"day":22,"count":31,"name":"Ahmad Ibhrahim Shbeir","age":24,"place":" Nusseirat"},
{"day":22,"count":32,"name":"Mohammad Jalal al-Jarf","age":24,"place":" Khan Younis"},
{"day":22,"count":33,"name":"Raed Salah","age":22,"place":" Al-Boreij"},
{"day":22,"count":34,"name":"Ahmad Nassim Saleh","age":23,"place":" Al-Boreij"},
{"day":22,"count":35,"name":"Mahmoud Ghanem","age":22,"place":"Al-Boreij"},
{"day":22,"count":36,"name":"Mustafa Mohammad Mahmoud Fayyad","age":24,"place":""},
{"day":22,"count":37,"name":"Ahmad Issam Wishah","age":29,"place":" Central District"},
{"day":22,"count":38,"name":"Ahmad Kamel Abu Mgheiseb","age":35,"place":" Central District"},
{"day":22,"count":39,"name":"Raed Abdul-Rahman Abu Mgheiseb","age":35,"place":" Central District"},
{"day":22,"count":40,"name":"Nader Abdul-Rahman Abu Mgheiseb","age":35,"place":" Central District"},
{"day":22,"count":41,"name":"Ahmad Mohammad Ramadan","age":30,"place":" Central District"},
{"day":22,"count":42,"name":"Khalaf Atiyya Abu Sneima","age":18,"place":" Rafah"},
{"day":22,"count":43,"name":"Khalil Atiyya Abu Sneima","age":20,"place":" Rafah"},
{"day":22,"count":44,"name":"Samih Abu Jalala","age":64,"place":" Rafah"},
{"day":22,"count":45,"name":"Hakima Nafe’ Abu ‘Adwan","age":75,"place":" Rafah"},
{"day":22,"count":46,"name":"Najah Nafe’ Abu ‘Adwan","age":85,"place":" Rafah"},
{"day":22,"count":47,"name":"Mohammad Shehada Hajjaj","age":31,"place":" Rafah"},
{"day":22,"count":48,"name":"Fawza Saleh Abdul-Rahman Hajjaj","age":66,"place":" Rafah"},
{"day":22,"count":49,"name":"Rawan Ziad Jom’a Hajjaj","age":28,"place":"Gaza City"},
{"day":22,"count":50,"name":"Mos’ab Nafeth al-Ejla","age":30,"place":" Shuja’eyya Gaza"},
{"day":22,"count":51,"name":"Tareq Fayeq Hajjaj","age":22,"place":" Gaza"},
{"day":22,"count":52,"name":"Ahmad Ziad Hajjaj","age":21,"place":"Gaza"},
{"day":22,"count":53,"name":"Hasan Sha’ban Khamisy","age":28,"place":" Gaza"},
{"day":22,"count":54,"name":"Ahmad As’ad al-Boudi","age":24,"place":" Beit Lahia"},
{"day":22,"count":55,"name":"Ahmad Salah Abu Seedo","age":17,"place":" Gaza"},
{"day":22,"count":56,"name":"Salem Khalil Salem Shammaly","age":23,"place":" Shujaeyya - Gaza Killed Sunday"},
{"day":22,"count":57,"name":"Ibrahim Sammour","age":38,"place":" Khan Younis"},
{"day":22,"count":58,"name":"Atiyya ad-Da’alsa","age":null,"place":"Nusseirat"},
{"day":22,"count":59,"name":"Abdullah Awni al-Farra","age":25,"place":" Khan Younis"},
{"day":22,"count":60,"name":"Hamada ‘Olewa","age":null,"place":" Zaitoun found under the rubble of his home"},
{"day":22,"count":61,"name":"Ibrahim Sobhi al-Fayre","age":null,"place":"Jabalia"},
{"day":22,"count":62,"name":"Rafiq Mohammad Qlub","age":null,"place":"Jabalia"},
{"day":22,"count":63,"name":"Ahmad Abu Salah","age":null,"place":" Khan Younis"},
{"day":22,"count":64,"name":"Mohammad Abdul-Karim Abu Jame’","age":null,"place":"Khan Younis"},
{"day":22,"count":65,"name":"Amjad al-Hindi","age":null,"place":" Gaza City"},
{"day":21,"count":1,"name":"Shahinaz Walid Mohammad Abu Hamad","age":1,"place":" Khan Younis"},
{"day":21,"count":2,"name":"Husam Abu Qeinas","age":5,"place":" Khan Younis"},
{"day":21,"count":3,"name":"Somoud Nassr Siyam","age":26,"place":" Gaza City"},
{"day":21,"count":4,"name":"Bader Nabil Siyam","age":25,"place":" Gaza City"},
{"day":21,"count":5,"name":"Ahmad Ayman Mahrous Siyam","age":17,"place":" Gaza City"},
{"day":21,"count":6,"name":"Mustafa Nabil Mahrous Siyam","age":12,"place":" Gaza City"},
{"day":21,"count":7,"name":"Ghaida’ Nabil Mahrous Siyam","age":8,"place":" Gaza City"},
{"day":21,"count":8,"name":"Dalal Nabil Mahrous Siyam","age":2,"place":" Gaza City"},
{"day":21,"count":9,"name":"Kamal Mahrous Salama Siyam","age":27,"place":" Gaza City"},
{"day":21,"count":10,"name":"Mohammad Mahrous Salaam Siyam","age":25,"place":" Gaza City"},
{"day":21,"count":11,"name":"Shireen Mahmoud Salaam Siyam","age":32,"place":" Gaza City"},
{"day":21,"count":12,"name":"Jowdat Tawfiq Ahmad Abu Jame’","age":24,"place":" Khan Younis"},
{"day":21,"count":13,"name":"Tawfiq Ahmad Abu Jame’","age":5,"place":" Khan Younis"},
{"day":21,"count":14,"name":"Haifa Tawfiq Ahmad Abu Jame’","age":9,"place":" Khan Younis"},
{"day":21,"count":15,"name":"Yasmin Ahmad Salama Abu Jame’","age":25,"place":" Khan Younis"},
{"day":21,"count":16,"name":"Soheila Bassam Abu Jame’","age":null,"place":" Khan Younis"},
{"day":21,"count":17,"name":"Roseanne Tawfiq Ahmad Abu Jame’","age":14,"place":" Khan Younis"},
{"day":21,"count":18,"name":"Child from Abu Jame’ family","age":null,"place":" name not yet confirmed"},
{"day":21,"count":19,"name":"Child from Abu Jame’ family","age":null,"place":" name not yet confirmed"},
{"day":21,"count":20,"name":"Woman from Abu Jame’ family","age":null,"place":" name not yet confirmed"},
{"day":21,"count":21,"name":"Ahmad Suleiman Abu Saoud","age":34,"place":" Khan Younis"},
{"day":21,"count":22,"name":"Manwa AbdulBaset asSabe’","age":37,"place":" Beit Hanoun"},
{"day":21,"count":23,"name":"Kamal Balal alMasri","age":22,"place":" Beit Hanoun"},
{"day":21,"count":24,"name":"Bilal Jabr Mohammad alAshab","age":22,"place":" Gaza City"},
{"day":21,"count":25,"name":"Raed Ismail alBardawil","age":26,"place":" Rafah"},
{"day":21,"count":26,"name":"Zakariya Masoud alAshqar","age":24,"place":" central Gaza"},
{"day":21,"count":27,"name":"Abdullah Matroud Abu Hjeir","age":16,"place":" central Gaza"},
{"day":21,"count":28,"name":"Ahmad Salhoub","age":34,"place":" central Gaza"},
{"day":21,"count":29,"name":"Raed Issam Daoud","age":30,"place":" Gaza City"},
{"day":21,"count":30,"name":"Younis Ahmad Younis Sheikh alEid","age":23,"place":" Rafah"},
{"day":21,"count":31,"name":"Raja'e Hammad Mohammad","age":38,"place":" Gaza"},
{"day":21,"count":32,"name":"Ahmad Khale Daghmash","age":21,"place":" Gaza"},
{"day":21,"count":33,"name":"Mahmoud Hasan anNakhala","age":null,"place":" Gaza"},
{"day":21,"count":34,"name":"Saleh Badawi","age":31,"place":" Gaza"},
{"day":21,"count":35,"name":"Kamal Mas’oud","age":21,"place":" Gaza"},
{"day":21,"count":36,"name":"Mohammad Samih alGhalban","age":null,"place":" Gaza"},
{"day":21,"count":37,"name":"Majdi Mahmoud alYazeji","age":56,"place":" alKarama Gaza"},
{"day":21,"count":38,"name":"Mayar al Yazeji","age":2,"place":" alKarama Gaza"},
{"day":21,"count":39,"name":"Anas al Yazeji","age":5,"place":" alKarama Gaza"},
{"day":21,"count":40,"name":"Yasmin Naif alYazeji","age":null,"place":" Gaza alKarama"},
{"day":21,"count":41,"name":"Safinaz alYazeji","age":null,"place":" Gaza alKarama"},
{"day":21,"count":42,"name":"Tamer Nayef Jundiyya","age":30,"place":" Gaza"},
{"day":21,"count":43,"name":"Kamel Jundiyya","age":32,"place":" Gaza"},
{"day":21,"count":44,"name":"Rahma Ahmad Jundiyya","age":50,"place":" "},
{"day":21,"count":45,"name":"Mohammad Mahmoud alMaghrebi","age":24,"place":" "},
{"day":21,"count":46,"name":"Ibrahim Sha’ban Bakron","age":37,"place":" "},
{"day":21,"count":47,"name":"Yousef Ghazi Hamdiyya","age":25,"place":" Gaza"},
{"day":21,"count":48,"name":"Mo’taz Jamal Hamdiyya","age":18,"place":" Gaza"},
{"day":21,"count":49,"name":"‘Aaed Jamal Hamdiyya","age":21,"place":" Gaza"},
{"day":21,"count":50,"name":"Yasmin alQisas","age":null,"place":" Gaza City"},
{"day":21,"count":51,"name":"Lamia Eyad alQisas","age":null,"place":" Gaza City"},
{"day":21,"count":52,"name":"Nismaa Eyad alQisas","age":null,"place":" Gaza City"},
{"day":21,"count":53,"name":"Arwa alQisas","age":null,"place":" Gaza City"},
{"day":21,"count":54,"name":"Aya Yassr alQisas","age":null,"place":" Gaza City"},
{"day":21,"count":55,"name":"Aisha’ Yassr alQisas","age":null,"place":" Gaza City"},
{"day":21,"count":56,"name":"Aliya Siyam","age":null,"place":" Gaza City"},
{"day":21,"count":57,"name":"Fayza Sabr Siyam","age":null,"place":" Gaza City"},
{"day":21,"count":58,"name":"Samia Siyam","age":null,"place":" Gaza City"},
{"day":21,"count":59,"name":"Fadi ‘Azmi Buryam","age":null,"place":" Deir alBalah"},
{"day":21,"count":60,"name":"Ayman Salaam Buryam","age":null,"place":" Deir alBalah"},
{"day":21,"count":61,"name":"Salaam AbdulMajeed Buryam","age":null,"place":" Deir alBalah"},
{"day":21,"count":62,"name":"Karim Ibrahim ‘Atiya Barham","age":25,"place":" Khan Younis"},
{"day":21,"count":63,"name":"Nidal Ali Daka’","age":26,"place":" Khan Younis"},
{"day":21,"count":64,"name":"Nidal Jamaa’ Abu ‘Asy","age":43,"place":" Khan Younis"},
{"day":21,"count":65,"name":"Fatima Ahmad alArja","age":null,"place":" Rafah"},
{"day":21,"count":66,"name":"Atiya Yusef Dardouna","age":26,"place":" Jabalia"},
{"day":21,"count":67,"name":"Ibrahim Deib Ahmad alKilani","age":53,"place":" Gaza City"},
{"day":21,"count":68,"name":"Yassr Ibrahim Deib alKilani","age":8,"place":" Gaza City"},
{"day":21,"count":69,"name":"Elias Ibrahim Deib alKilani","age":4,"place":" Gaza City"},
{"day":21,"count":70,"name":"Susan Ibrahim Deib alKilani","age":11,"place":" Gaza City"},
{"day":21,"count":71,"name":"Reem Ibrahim Deib alKilani","age":12,"place":" Gaza City"},
{"day":21,"count":72,"name":"Yasmeen Ibrahim Deeb alKilani","age":9,"place":" Gaza City"},
{"day":21,"count":73,"name":"Taghrid Shoeban Mohammad alKilani","age":45,"place":" Gaza City"},
{"day":21,"count":74,"name":"Aida’ Shoeban Mohammad Derbas","age":47,"place":" Gaza City"},
{"day":21,"count":75,"name":"Mahmoud Shoeban Mohammad Derbas","age":37,"place":" Gaza City"},
{"day":21,"count":76,"name":"Sura Shoeban Mohammad Derbas","age":41,"place":" Gaza City"},
{"day":21,"count":77,"name":"Aynas Shoeban Mohammad Derbas","age":30,"place":" Gaza City"},
{"day":21,"count":78,"name":"Fadi Bashir alAblala","age":22,"place":" Khan Younis"},
{"day":20,"count":1,"name":"Salem Ali Abu Sa'ada","age":null,"place":" Khan Younis"},
{"day":20,"count":2,"name":"Mohammad Yusef Moammer","age":30,"place":" Rafah"},
{"day":20,"count":3,"name":"Hamza Yousef Moammer","age":26,"place":" Rafah"},
{"day":20,"count":4,"name":"Anas Yousef Moammar","age":16,"place":" "},
{"day":20,"count":5,"name":"Hosni Mahmoud alAbsi","age":56,"place":" Rafah"},
{"day":20,"count":6,"name":"Suheib Ali Jom’a Abu Qoura","age":21,"place":" Rafah"},
{"day":20,"count":7,"name":"Ahmad Tawfiq Mohammad Za’noun","age":26,"place":" Rafah"},
{"day":20,"count":8,"name":"Hamid Soboh Mohammad Fojo","age":22,"place":" Rafah"},
{"day":20,"count":9,"name":"Najah Sa’ad alDeen Daraji","age":65,"place":" Rafah"},
{"day":20,"count":10,"name":"Abdullah Yusef Daraji","age":3,"place":" Rafah"},
{"day":20,"count":11,"name":"Mohammed Raja'a Handam 15","age":null,"place":" Rafah"},
{"day":20,"count":12,"name":"Yusef Sha’aban Ziada","age":44,"place":" Al Bureij"},
{"day":20,"count":13,"name":"Jamil Sha’aban Ziada","age":53,"place":" Al Bureij"},
{"day":20,"count":14,"name":"Shoeban Jamil Ziada","age":12,"place":" Al Bureij son of Jamil"},
{"day":20,"count":15,"name":"Soheiib Abu Ziada","age":null,"place":" Al Bureij"},
{"day":20,"count":16,"name":"Mohammad Mahmoud alMoqaddma","age":30,"place":" Al Bureij"},
{"day":20,"count":17,"name":"Raed Mansour Nayfa","age":null,"place":" Shujaeyya Gaza City"},
{"day":20,"count":18,"name":"Fuad Jaber","age":null,"place":" Shujaeyya Gaza CityMedic"},
{"day":20,"count":19,"name":"Mohammad Hani Mohammad alHallaq","age":2,"place":" alRimal Gaza City"},
{"day":20,"count":20,"name":"Kenan Hasan Akram alHallaq","age":6,"place":" alRimal  Gaza"},
{"day":20,"count":21,"name":"Hani Mohammad alHallaq","age":29,"place":" alRimal Gaza City"},
{"day":20,"count":22,"name":"Suad Mohammad alHallaq","age":62,"place":" alRimal Gaza City"},
{"day":20,"count":23,"name":"Saje Hasan Akram alHallaq","age":4,"place":" alRimal Gaza City"},
{"day":20,"count":24,"name":"Hala Akram Hasan alHallaq","age":27,"place":" alRimal Gaza City"},
{"day":20,"count":25,"name":"Samar Osama alHallaq","age":29,"place":" alRimal Gaza City"},
{"day":20,"count":26,"name":"Ahmad Yassin","age":null,"place":"alRimal Gaza City"},
{"day":20,"count":27,"name":"Ismael Yassin","age":null,"place":" alRimal Gaza City"},
{"day":20,"count":28,"name":"Aya Bahjat Abu Sultan","age":15,"place":" Beit Lahia"},
{"day":20,"count":29,"name":"Rayan Taysir Abu Jame’","age":8,"place":" Khan Younis"},
{"day":20,"count":30,"name":"Fatima Mahmoud Abu Jame’","age":3,"place":" Khan Younis"},
{"day":20,"count":31,"name":"Suleiman Abu Jame’","age":null,"place":" Khan Younis"},
{"day":20,"count":32,"name":"Ibrahim Salem Jom’a asSahbani","age":20,"place":" Shujaeyya  Gaza"},
{"day":20,"count":33,"name":"‘Aref Ibrahim alGhalyeeni","age":26,"place":" Shujaeyya  Gaza"},
{"day":20,"count":34,"name":"Osama Khalil Ismael alHayya","age":30,"place":" Shujaeyya  Gaza father of Umama and Khalil"},
{"day":20,"count":35,"name":"Hallah Saqer Hasan alHayya","age":29,"place":" Shujaeyya – Gaza mother of Umama and Khalil"},
{"day":20,"count":36,"name":"Umama Osama Khalil alHayya","age":9,"place":" Shujaeyya  Gaza"},
{"day":20,"count":37,"name":"Khalil Osama Khalil alHayya","age":7,"place":" Shujaeyya  Gaza"},
{"day":20,"count":38,"name":"Rebhi Shehta ‘Ayyad","age":31,"place":" Shujaeyya  Gaza"},
{"day":20,"count":39,"name":"Yasser Ateyya Hamdiyya","age":28,"place":" Shujaeyya  Gaza"},
{"day":20,"count":40,"name":"Esra’ Ateyya Hamdiyya","age":28,"place":" Shujaeyya  Gaza"},
{"day":20,"count":41,"name":"Akram Mohammad Shkafy","age":63,"place":" Shujaeyya  Gaza"},
{"day":20,"count":42,"name":"Eman Khalil Abed ‘Ammar","age":9,"place":" Shujaeyya  Gaza"},
{"day":20,"count":43,"name":"Ibrahim Khalil Abed Ammar","age":13,"place":" Shujaeyya  Gaza"},
{"day":20,"count":44,"name":"‘Asem Khalil Abed Ammar","age":4,"place":" Shujaeyya  Gaza"},
{"day":20,"count":45,"name":"Eman Mohammad Ibrahim Hamada","age":40,"place":" Shujaeyya  Gaza"},
{"day":20,"count":46,"name":"Ahmad Ishaq Yousef Ramlawy","age":33,"place":" Shujaeyya  Gaza"},
{"day":20,"count":47,"name":"Ahmad Sami Diab ‘Ayyad","age":27,"place":" Shujaeyya  Gaza"},
{"day":20,"count":48,"name":"Fida’ Rafiq Diab ‘Ayyad","age":24,"place":" Shujaeyya  Gaza"},
{"day":20,"count":49,"name":"Narmin Rafiw Diab Ayyad","age":20,"place":" Shujaeyya  Gaza"},
{"day":20,"count":50,"name":"Ahmad Mohammad Ahmad Abu Za’nouna","age":28,"place":" "},
{"day":20,"count":51,"name":"Tala Akram Ahmad al‘Atawy","age":7,"place":" Shujaeyya  Gaza"},
{"day":20,"count":52,"name":"Tawfiq Barawi Salem Marshoud","age":52,"place":" Shujaeyya  Gaza"},
{"day":20,"count":53,"name":"Hatem Ziad Ali Za’bout","age":24,"place":" Shujaeyya  Gaza"},
{"day":20,"count":54,"name":"Khaled Riyadh Mohammad Hamad","age":25,"place":" Shujaeyya Gaza Journalist"},
{"day":20,"count":55,"name":"Khadija Ali Mousa Shihada","age":62,"place":" Shujaeyya  Gaza"},
{"day":20,"count":56,"name":"Khalil Salem Ibrahim Mosbeh","age":53,"place":" Shujaeyya  Gaza"},
{"day":20,"count":57,"name":"‘Adel Abdullah Eslayyem","age":2,"place":" Shujaeyya  Gaza"},
{"day":20,"count":58,"name":"Dina Roshdi Abdullah Eslayyem","age":2,"place":" Shujaeyya  Gaza"},
{"day":20,"count":59,"name":"Rahaf Akram Ismael Abu Jom’a","age":4,"place":" Shujaeyya  Gaza"},
{"day":20,"count":60,"name":"Shadi Ziad Hasan Eslayyem","age":15,"place":" Shujaeyya  Gaza"},
{"day":20,"count":61,"name":"Ala Ziad Hasan Eslayyem","age":11,"place":" Shujaeyya  Gaza"},
{"day":20,"count":62,"name":"Sherin Fathi Othman Ayyad","age":18,"place":" Shujaeyya  Gaza"},
{"day":20,"count":63,"name":"‘Adel Abdullah Salem Eslayyem","age":29,"place":" Shujaeyya  Gaza"},
{"day":20,"count":64,"name":"Fadi Ziad Hasan Eslayyem","age":10,"place":" Shujaeyya  Gaza"},
{"day":20,"count":65,"name":"‘Ahed Sa’ad Mousa Sarsak","age":30,"place":" Shujaeyya  Gaza"},
{"day":20,"count":66,"name":"Aisha Ali Mahmoud Zayed","age":54,"place":" Shujaeyya  Gaza"},
{"day":20,"count":67,"name":"AbedRabbo Ahmad Zayed","age":58,"place":" Shujaeyya  Gaza"},
{"day":20,"count":68,"name":"AbdulRahman Akram Sheikh Khalil","age":24,"place":" Shujaeyya  Gaza"},
{"day":20,"count":69,"name":"Mona Suleiman Ahmad Sheikh Khalil","age":49,"place":" "},
{"day":20,"count":70,"name":"Heba Hamed Mohammad Sheikh Khalil","age":13,"place":" Shujaeyya  Gaza"},
{"day":20,"count":71,"name":"Abdullah Mansour Radwan ‘Amara","age":23,"place":" Shujaeyya  Gaza"},
{"day":20,"count":72,"name":"Issam Atiyya Sa’id Skafy","age":26,"place":" Shujaeyya  Gaza"},
{"day":20,"count":73,"name":"Ali Mohammad Hasan Skafy","age":27,"place":" Shujaeyya  Gaza"},
{"day":20,"count":74,"name":"Mohammad Hasan Skafy","age":53,"place":" Shujaeyya  Gaza"},
{"day":20,"count":75,"name":"‘Ala Jamal edDeen Barda’","age":35,"place":" Shujaeyya  Gaza"},
{"day":20,"count":76,"name":"Omar Jamil Sobhi Hammouda","age":10,"place":" Shujaeyya  Gaza"},
{"day":20,"count":77,"name":"Ghada Jamil Sobhi Hammouda","age":10,"place":" Shujaeyya  Gaza"},
{"day":20,"count":78,"name":"Ghada Ibrahim Suleiman ‘Adwan","age":39,"place":" Shujaeyya  Gaza"},
{"day":20,"count":79,"name":"Fatima AbdulRahim Abu Ammouna","age":55,"place":" Shujaeyya  Gaza"},
{"day":20,"count":80,"name":"Fahmi AbdulAziz Abu Sa’id","age":29,"place":" Shujaeyya  Gaza"},
{"day":20,"count":81,"name":"Ghada Sobhi Sa’adi Ayyad","age":9,"place":" Shujaeyya  Gaza"},
{"day":20,"count":82,"name":"Mohammad Ashraf Rafiq Ayyad","age":6,"place":" Shujaeyya  Gaza"},
{"day":20,"count":83,"name":"Mohammad Ra’ed Ehsan Ayyad","age":6,"place":" Shujaeyya  Gaza"},
{"day":20,"count":84,"name":"Mohammad Rami Fathi ‘Ayyad","age":2,"place":" Shujaeyya  Gaza"},
{"day":20,"count":85,"name":"Mohammad Ra’ed Ehsan ‘Akeela","age":19,"place":" Shujaeyya  Gaza"},
{"day":20,"count":86,"name":"Mohammad Ziad Ali Za’bout","age":23,"place":" Shujaeyya  Gaza"},
{"day":20,"count":87,"name":"Mohammad Ali Mohared Jundiyya","age":38,"place":" Shujaeyya  Gaza"},
{"day":20,"count":88,"name":"Marah Shaker Ahmad alJammal","age":2,"place":" Shujaeyya  Gaza"},
{"day":20,"count":89,"name":"Marwan Monir Saleh Qonfid","age":23,"place":" Shujaeyya  Gaza"},
{"day":20,"count":90,"name":"Maisa AbdulRahman Sarsawy","age":37,"place":" Shujaeyya  Gaza"},
{"day":20,"count":91,"name":"Marwa Salman Ahmad Sarsawy","age":13,"place":" Shujaeyya  Gaza"},
{"day":20,"count":92,"name":"Mos’ab elKheir Salah edDin Skafi","age":27,"place":" Shujaeyya  Gaza"},
{"day":20,"count":93,"name":"Mona AbdulRahman Ayyad","age":42,"place":" Shujaeyya  Gaza"},
{"day":20,"count":94,"name":"Halla Sobhi Sa’dy Ayyad","age":25,"place":" Shujaeyya  Gaza"},
{"day":20,"count":95,"name":"Younis Ahmad Younis Mustafa","age":62,"place":" Shujaeyya  Gaza"},
{"day":20,"count":96,"name":"Yousef Salem Hatmo Habib","age":62,"place":" Shujaeyya  Gaza"},
{"day":20,"count":97,"name":"Fatima Abu Ammouna","age":55,"place":" Shujaeyya – Gaza"},
{"day":20,"count":98,"name":"Ahmad Mohammad Azzam","age":19,"place":" Shujaeyya – Gaza"},
{"day":20,"count":99,"name":"Ismael alKordi","age": null,"place":"Shujaeyya – Gaza"},
{"day":19,"count":1,"name":"Yahia Bassam asSerry","age":20,"place":" Khan Younis"},
{"day":19,"count":2,"name":"Mohammad Bassam asSerry","age":17,"place":" Khan Younis"},
{"day":19,"count":3,"name":"Mahmoud Rida Salhiyya","age":56,"place":" Khan Younis"},
{"day":19,"count":4,"name":"Mustafa Rida Salhiyya","age":21,"place":" Khan Younis"},
{"day":19,"count":5,"name":"Mohammad Mustafa Salhiyya","age":22,"place":" Khan Younis"},
{"day":19,"count":6,"name":"Waseem Rida Salhiyya","age":15,"place":" Khan Younis"},
{"day":19,"count":7,"name":"Ibrahim Jamal Kamal Nassr","age":13,"place":" Khan Younis"},
{"day":19,"count":8,"name":"Rushdi Khaled Nassr","age":24,"place":" Khan Younis"},
{"day":19,"count":9,"name":"Mohammad Awad Faris Nassr","age":25,"place":" Khan Younis"},
{"day":19,"count":10,"name":"Ahmad Mahmoud Hasan Aziz","age":34,"place":" Beit Hanoun"},
{"day":19,"count":11,"name":"Sa’id Ali Issa","age":30,"place":" Juhr edDeekCentral Gaza"},
{"day":19,"count":12,"name":"Raed Walid Laqan","age":27,"place":" Khan Younis"},
{"day":19,"count":13,"name":"Mohammad Jihad alQara’","age":29,"place":" Khan Younis"},
{"day":19,"count":14,"name":"Rafat Ali Bahloul","age":36,"place":" Khan Younis"},
{"day":19,"count":15,"name":"Bilal Ismail Abu Doqqa","age":33,"place":" Khan Younis"},
{"day":19,"count":16,"name":"Mohammad Ismail Sammour","age":21,"place":" Khan Younis"},
{"day":19,"count":17,"name":"Eyad Ismael arRaqab","age":26,"place":" Khan Younis"},
{"day":19,"count":18,"name":"Mohammad Atallah Odah Sa’adat","age":25,"place":" Beit Hanoun"},
{"day":19,"count":19,"name":"Mohammad Rafiq arRohhal","age":22,"place":" Beit Lahia"},
{"day":19,"count":20,"name":"Mohammad Ziad arRohhal","age":6,"place":" Beit Lahia"},
{"day":19,"count":21,"name":"Mohammad Ahmad Abu Za’nouna","age":37,"place":" Gaza City"},
{"day":19,"count":22,"name":"Mahmoud AbdulHamid alZweidi","age":23,"place":" Beit Lahia"},
{"day":19,"count":23,"name":"Dalia AbdelHamid alZweidi","age":37,"place":" Beit Lahia"},
{"day":19,"count":24,"name":"Rowiya Mahmoud alZweidi","age":6,"place":" Beit Lahia"},
{"day":19,"count":25,"name":"Naghm Mahmoud alZweidi","age":2,"place":" Beit Lahia" },
{"day":19,"count":26,"name":"Mohammad Khaled Jamil alZweidi","age":20,"place":" Beit Lahia"},
{"day":19,"count":27,"name":"Amr Hamouda","age":7,"place":" Beit Lahia" },
{"day":19,"count":28,"name":"Mohammad Riziq Mohammad Hamouda","age":18,"place":" "},
{"day":19,"count":29,"name":"Mo’men Taysir al‘Abed Abu Dan","age":24,"place":" Central District" },
{"day":19,"count":30,"name":"AbdulAziz Samir Abu Za’itar","age":31,"place":" Central District"},
{"day":19,"count":31,"name":"Mohammad Ziad Za’bout","age":24,"place":" Gaza City"},
{"day":19,"count":32,"name":"Hatem Ziad Za’bout","age":22,"place":"Gaza City"},
{"day":19,"count":33,"name":"Fadal Mohammad alBana","age":29,"place":" was killed in Jabalia"},
{"day":19,"count":34,"name":"Mohammad AbdulRahman Abu Hamad","age":25,"place":" Beit Lahia"},
{"day":19,"count":35,"name":"Ma’ali AbdulRahman Suleiman Abu Zeid","age":24,"place":" Central District"},
{"day":19,"count":36,"name":"Mohammad Ahmad asSaidi","age":18,"place":" Khan Younis"},
{"day":19,"count":37,"name":"AbdulRahman Mohammad Odah","age":23,"place":" Central District"},
{"day":19,"count":38,"name":"Tariq Samir Khalil alHatou","age":26,"place":" Central District"},
{"day":19,"count":39,"name":"Mahmoud alSharif","age":24,"place":" Central District"},
{"day":19,"count":40,"name":"Mohammad Fathi alGhalban","age":23,"place":" Khan Younis"},
{"day":19,"count":41,"name":"Mahmoud Anwar Abu Shabab","age":16,"place":" Rafah"},
{"day":19,"count":42,"name":"Ahmad Abu Thurayya","age":25,"place":" Central District"},
{"day":19,"count":43,"name":"Abdullah Ghazi alMasri","age":30,"place":" Central District"},
{"day":19,"count":44,"name":"Ayman Hisham anNa’ouq","age":25,"place":" Central District"},
{"day":19,"count":45,"name":"Aqram Mahmoud alMatouq","age":37,"place":" Jabalia"},
{"day":18,"count":1,"name":"Majdi Suleiman Jabara","age":22,"place":" Rafah"},
{"day":18,"count":2,"name":"Faris Juma’ alMahmoum","age":1,"place":" Rafah"},
{"day":18,"count":3,"name":"Omar ‘Eid alMahmoum","age":18,"place":" Rafah"},
{"day":18,"count":4,"name":"Nassim Mahmoud Nassier","age":22,"place":" Beit Hanoun"},
{"day":18,"count":5,"name":"Karam Mahmoud Nassier","age":20,"place":" Beit Hanoun"},
{"day":18,"count":6,"name":"Salmiyya Suleiman Ghayyadh","age":70,"place":" Rafah"},
{"day":18,"count":7,"name":"Rani Saqer Abu Tawila","age":30,"place":" Gaza City"},
{"day":18,"count":8,"name":"Hammad AbdulKarim Abu Lehya","age":23,"place":" Khan Younis"},
{"day":18,"count":9,"name":"Mohammad AbdulFattah Rashad Fayyad","age":26,"place":" Khan Younis"},
{"day":18,"count":10,"name":"Mahmoud Mohammad Fayyad","age":25,"place":" Khan Younis"},
{"day":18,"count":11,"name":"Amal Khader Ibrahim Dabbour","age":40,"place":" Beit Hanoun"},
{"day":18,"count":12,"name":"Ismail Yousef Taha Qassim","age":59,"place":" Beit Hanoun"},
{"day":18,"count":13,"name":"Ahmad Fawzi Radwan","age":23,"place":" Khan Younis"},
{"day":18,"count":14,"name":"Mahmoud Fawzi Radwan","age":24,"place":" Khan Younis"},
{"day":18,"count":15,"name":"Bilal Mahmoud Radwan","age":23,"place":" Khan Younis"},
{"day":18,"count":16,"name":"Monther Radwan","age":22,"place":" Khan Younis"},
{"day":18,"count":17,"name":"Hani As'ad AbdulKarim Shami","age":35,"place":" Khan Younis"},
{"day":18,"count":18,"name":"Mohammad Hamdan AbdulKarim Shami","age":35,"place":" Khan Younis"},
{"day":18,"count":19,"name":"Husam Musallam Abu Issa","age":26,"place":" Gaza City"},
{"day":18,"count":20,"name":"Ahmad Ismael Abu Musallam","age":14,"place":" Gaza City"},
{"day":18,"count":21,"name":"Mohammad Ismael Abu Musallam","age":15,"place":" Gaza City"},
{"day":18,"count":22,"name":"Wala’ Ismael Abu Musallam","age":13,"place":" Gaza City"},
{"day":18,"count":23,"name":"Naim Mousa Abu Jarad","age":23,"place":" Beit Hanoun"},
{"day":18,"count":24,"name":"Abed Mousa Abu Jarad","age":30,"place":" Beit Hanoun"},
{"day":18,"count":25,"name":"Siham Mousa Abu Jarad","age":26,"place":" Beit Hanoun"},
{"day":18,"count":26,"name":"Raja’ Oliyyan Abu Jarad","age":31,"place":" Beit Hanoun"},
{"day":18,"count":27,"name":"Haniyya AbdulRahman Abu Jarad","age":3,"place":" Beit Hanoun"},
{"day":18,"count":28,"name":"Samih Naim Abu Jarad","age":1,"place":" Beit Hanoun"},
{"day":18,"count":29,"name":"Mousa AbulRahman Abu Jarad","age":1,"place":" Beit Hanoun"},
{"day":18,"count":30,"name":"Ahlam Mousa Abu Jarad","age":13,"place":" Beit Hanoun"},
{"day":18,"count":31,"name":"Husam Musallam Abu Aisha","age":26,"place":" Jahr alDeek"},
{"day":18,"count":32,"name":"Mohammad Sa’ad Mahmoud Abu Sa’da ","age":null,"place":" Khan Younis"},
{"day":18,"count":33,"name":"Ra’fat Mohammad alBahloul","age":35,"place":" Khan Younis"},
{"day":18,"count":34,"name":"Wala’ alQarra","age":20,"place":" Khan Younis"},
{"day":18,"count":35,"name":"Abdullah Jamal asSmeiri","age":17,"place":" Khan Younis"},
{"day":18,"count":36,"name":"Ahmad Hasan Saleh alGhalban","age":23,"place":" Khan Younis"},
{"day":18,"count":37,"name":"Hamada Abdullah Mohammad alBashiti","age":21,"place":" Khan Younis"},
{"day":18,"count":38,"name":"Hamza Mohammad Abu Hussein","age":27,"place":" Rafah"},
{"day":18,"count":39,"name":"Ala’ Abu Shabab","age":23,"place":" Rafah"},
{"day":18,"count":40,"name":"Mohammad ‘Awad Matar","age":37,"place":" Rafah"},
{"day":18,"count":41,"name":"Bassem Mohammad Mahmoud Madhi","age":22,"place":" Rafah"},
{"day":18,"count":42,"name":"Ahmad Abdullah alBahnasawi","age":25,"place":" Um AnNasr"},
{"day":18,"count":43,"name":"Saleh ‘Zgheidy","age":20,"place":" Rafah"},
{"day":18,"count":44,"name":"Mahmoud Ali Darwish","age":40,"place":" Nusseirat Central Gaza"},
{"day":18,"count":45,"name":"Yousef Ibrahim alAstal","age":23,"place":"Khan Younis"},
{"day":18,"count":46,"name":"Imad Hamed E’lawwan","age":7,"place":" Gaza"},
{"day":18,"count":47,"name":"Qassem Hamed E’lawwan","age":4,"place":" Gaza City brother of Imad"},
{"day":18,"count":48,"name":"Sarah Mohammad Bustan","age":13,"place":" Gaza City"},
{"day":18,"count":49,"name":"Rezeq Ahmad alHayek","age":2,"place":" Gaza"},
{"day":18,"count":50,"name":"Mustafa Faisal Abu Sneina","age":32,"place":" Rafah"},
{"day":18,"count":51,"name":"Imad Faisal Abu Sneina","age":18,"place":" Rafah"},
{"day":18,"count":52,"name":"Nizar Fayez Abu Sneina","age":38,"place":" Rafah"},
{"day":18,"count":53,"name":"Ismail Ramadan alLoulahi","age":21,"place":" Khan Younis"},
{"day":18,"count":54,"name":"Ghassan Salem Mousa Abu ‘Azab","age":28,"place":" Khan Younis"},
{"day":18,"count":55,"name":"Ahmad Salem Sha’at","age":22,"place":" Khan Younis"},
{"day":18,"count":56,"name":"Mohammad Salem Sha’at","age":20,"place":" Khan Younis"},
{"day":18,"count":57,"name":"Amjad Salem Sha’at","age":15,"place":" Khan Younis"},
{"day":18,"count":58,"name":"Mohammad Talal asSane’","age":20,"place":" Rafah"},
{"day":17,"count":1,"name":"Mohammad Mahmoud AlQadim","age":22,"place":" Deir alBalah"},
{"day":17,"count":2,"name":"Mohammad AbdulRahman Hassouna","age":67,"place":" Rafah"},
{"day":17,"count":3,"name":"Zeinab Mohammad Sa’id al‘Abadla","age":71,"place":" Khan Younis"},
{"day":17,"count":4,"name":"Ahmad Reehan","age":23,"place":" Beit Lahia"},
{"day":17,"count":5,"name":"Salem Saleh Fayyad","age":25,"place":" Gaza City"},
{"day":17,"count":6,"name":"Abdullah Salem alAtras","age":27,"place":" Rafah"},
{"day":17,"count":7,"name":"Bashir Mohammad Abdul'Al","age":20,"place":" Rafah"},
{"day":17,"count":8,"name":"Mohammad Ziyad Ghanem","age":25,"place":" Rafah"},
{"day":17,"count":9,"name":"Mohammad Ahmad alHout","age":41,"place":" Rafah"},
{"day":17,"count":10,"name":"Fulla Tariq Shuhaibar","age":8,"place":" Gaza Cityrelated article"},
{"day":17,"count":11,"name":"Jihad Issam Shuhaibar","age":10,"place":" Gaza City related article"},
{"day":17,"count":12,"name":"Wasim Issam Shuhaibar","age":9,"place":" Gaza City related article"},
{"day":17,"count":13,"name":"Rahaf Khalil alJbour","age":4,"place":" Khan Younisrelated article"},
{"day":17,"count":14,"name":"Yassin alHumaidi","age":4,"place":" Gaza City died of earlier woundsrelated article"},
{"day":17,"count":15,"name":"Ismail Youssef alKafarneh","age":null,"place":" Beit Hanoun"},
{"day":17,"count":16,"name":"Hamza Hussein al'Abadala","age":29,"place":" Khan Younis"},
{"day":17,"count":17,"name":"Abed Ali Ntheir","age":26,"place":" Gaza City"},
{"day":17,"count":18,"name":"Mohammad Shadi Ntheir","age":15,"place":" Gaza Cityrelated article"},
{"day":17,"count":19,"name":"Mohammad Salem Ntheir","age":4,"place":" Gaza Cityrelated article"},
{"day":17,"count":20,"name":"Salah Saleh ashShafe’ey","age":null,"place":" Khan Younis"},
{"day":16,"count":1,"name":"Mohammad Ismael Abu Odah","age":27,"place":" Rafah"},
{"day":16,"count":2,"name":"Mohammad Abdullah Zahouq","age":23,"place":" Rafah"},
{"day":16,"count":3,"name":"Ahmed Adel Nawajha","age":23,"place":" Rafah"},
{"day":16,"count":4,"name":"Mohammad Taisir Abu Sharab","age":23,"place":" Khan Younis"},
{"day":16,"count":5,"name":"Mohammad Sabri adDebari","age":null,"place":" Rafah"},
{"day":16,"count":6,"name":"Farid Mahmoud AbuDoqqa","age":33,"place":" Khan Younis"},
{"day":16,"count":7,"name":"Ashraf Khalil Abu Shanab","age":33,"place":" Rafah"},
{"day":16,"count":8,"name":"Khadra AlAbed Salama Abu Doqqa","age":65,"place":" Khan Younis related article"},
{"day":16,"count":9,"name":"Omar Ramadan Abu Doqqa","age":24,"place":" Khan Younis related article"},
{"day":16,"count":10,"name":"Ibrahim Ramadan Abu Doqqa","age":10,"place":" Khan Younis related article"},
{"day":16,"count":11,"name":"Ahed Atef Bakr","age":10,"place":" Gaza beach related article"},
{"day":16,"count":12,"name":"Zakariya Ahed Bakr","age":10,"place":" Gaza beach related article"},
{"day":16,"count":13,"name":"Mohammad Ramiz Bakr","age":11,"place":" Gaza beach related article"},
{"day":16,"count":14,"name":"Ismail Mahmoud Bakr","age":9,"place":" Gaza beachrelated article"},
{"day":16,"count":15,"name":"Mohammad Kamel AbdulRahman","age":30,"place":" Sheikh 'EjleenGaza City"},
{"day":16,"count":16,"name":"Husam Shamlakh","age":23,"place":" Sheikh 'EjleenGaza City"},
{"day":16,"count":17,"name":"Usama Mahmoud AlAstal","age":6,"place":" Khan Younis"},
{"day":16,"count":18,"name":"Hussein AbdulNasser alAstal","age":23,"place":" Khan Younis"},
{"day":16,"count":19,"name":"Kawthar alAstal","age":70,"place":" Khan Younis"},
{"day":16,"count":20,"name":"Yasmin alAstal","age":4,"place":" Khan Younis"},
{"day":16,"count":21,"name":"Kamal Mohammad Abu 'Amer","age":38,"place":" Khan Younis"},
{"day":16,"count":22,"name":"Akram Mohammad Abu 'Amer","age":34,"place":" Khan Younisnull"},
{"day":16,"count":23,"name":"Hamza Raed Thary","age":6,"place":" Jabalia was injured a few days ago in the incident in which many"},
{"day":16,"count":24,"name":"AbdulRahman Ibrahim Khalil asSarhi","age":37,"place":" Gaza City"},
{"day":15,"count":1,"name":"Abdullah Mohammad al‘Arjani","age":19,"place":" Khan Younis"},
{"day":15,"count":2,"name":"Suleiman Abu Louly","age":33,"place":" Rafah"},
{"day":15,"count":3,"name":"Saleh Sa’id Dahleez","age":20,"place":" Rafah"},
{"day":15,"count":4,"name":"Yasser Eid alMahmoum","age":18,"place":" Rafah"},
{"day":15,"count":5,"name":"Ismael Fattouh Ismael","age":24,"place":" Gaza City"},
{"day":15,"count":6,"name":"Khalil Sh’aafy","age": null,"place":" Juhr EdDeek – Gaza"},
{"day":15,"count":7,"name":"Sobhi Abdulhamid Mousa","age":77,"place":" Khan Younis"},
{"day":14,"count":1,"name":"Adham AbdulFattah Abdul‘Aal","age":27,"place":" "},
{"day":14,"count":2,"name":"Hamid Suleiman Abu al‘Araj","age":60,"place":" Deir alBalah"},
{"day":14,"count":3,"name":"Abdullah Mahmoud Baraka","age":24,"place":" Khan Younis"},
{"day":14,"count":4,"name":"Tamer Salem Qdeih","age":37,"place":" Khan Younis"},
{"day":14,"count":5,"name":"Ziad Maher anNajjar","age":17,"place":" Khan Younis"},
{"day":14,"count":6,"name":"Ziad Salem ashShawy","age":25,"place":" Rafah"},
{"day":14,"count":7,"name":"Mohammad Yasser Hamdan","age":24,"place":" Gaza"},
{"day":14,"count":8,"name":"Mohammad Shakib alAgha","age":22,"place":" Khan Younis"},
{"day":14,"count":9,"name":"Ahmed Younis Abu Yousef","age":22,"place":" Khan Younis"},
{"day":14,"count":10,"name":"Sara Omar Sheikh alEid","age":4,"place":" Rafah"},
{"day":14,"count":11,"name":"Omar Ahmad Sheikh alEid","age":24,"place":" Rafah"},
{"day":14,"count":12,"name":"Jihad Ahmad Sheikh alEid","age":48,"place":" Rafah"},
{"day":14,"count":13,"name":"Kamal Atef Yousef Abu Taha","age":16,"place":" Khan Younis"},
{"day":14,"count":14,"name":"Ismael Nabil Ahmad Abu Hatab","age":21,"place":" Khan Younis"},
{"day":14,"count":15,"name":"Boshra Khalil Zo'rob","age":53,"place":" Rafah"},
{"day":14,"count":16,"name":"Atwa 'Amira al'Amour","age":63,"place":" Khan Younis"},
{"day":13,"count":1,"name":"Ezzeddin Bolbol","age":25,"place":" Rafah"},
{"day":13,"count":2,"name":"Rami Abu Shanab","age":25,"place":" Deir alBalah"},
{"day":13,"count":3,"name":"Fawziyya Abdulal","age":73,"place":" Gaza City"},
{"day":13,"count":4,"name":"Mo’ayyad al‘Araj","age":3,"place":" Khan Younis"},
{"day":13,"count":5,"name":"Husam Ibrahim Najjar","age":14,"place":" Jabalia"},
{"day":13,"count":6,"name":"Hijaziyya Hamed alHilo","age":80,"place":" Gaza City"},
{"day":13,"count":7,"name":"Ruwaida abu Harb Zawayda","age":30,"place":" central Gaza"},
{"day":13,"count":8,"name":"Haitham Ashraf Zo’rob","age":21,"place":" Rafah"},
{"day":13,"count":9,"name":"Laila Hassan al‘Odaat","age":41,"place":" alMaghazi"},
{"day":13,"count":10,"name":"Hussein AbdulQader Mheisin","age":19,"place":" Gaza"},
{"day":13,"count":11,"name":"Qassem Talal Hamdan","age":23,"place":" Beit Hanoun"},
{"day":13,"count":12,"name":"Maher Thabet abu Mour","age":23,"place":" Khan Younis"},
{"day":13,"count":13,"name":"Mohammad Salem Abu Breis","age":65,"place":" Deir alBalah"},
{"day":13,"count":14,"name":"Moussa Shehda Moammer","age":60,"place":" Khan Younis"},
{"day":13,"count":15,"name":"Hanadi Hamdi Moammer","age":27,"place":" Khan Younis"},
{"day":13,"count":16,"name":"Saddam Mousa Moammer","age":23,"place":" Khan Younis"},
{"day":12,"count":1,"name":"Anas Yousef Qandil","age":17,"place":" Jabalia"},
{"day":12,"count":2,"name":"Islam Yousef Mohammad Qandil","age":27,"place":" Jabalia"},
{"day":12,"count":3,"name":"Mohammad Edrees Abu Sneina","age":20,"place":" Jabalia"},
{"day":12,"count":4,"name":"AbdulRahim Saleh alKhatib","age":38,"place":" Jabalia"},
{"day":12,"count":5,"name":"Husam Thieb arRazayna","age":39,"place":" Jabalia"},
{"day":12,"count":6,"name":"Ibrahim Nabil Hamada","age":30,"place":" atTuffah  Gaza City"},
{"day":12,"count":7,"name":"Hasan Ahmad Abu Ghush","age":24,"place":" atTuffah  Gaza City"},
{"day":12,"count":8,"name":"Ahmad Mahmoud alBal’awy","age":26,"place":" atTuffah  Gaza City"},
{"day":12,"count":9,"name":"Ali Nabil Basal","age":32,"place":" atTuffah  Gaza City"},
{"day":12,"count":10,"name":"Mohammad Bassem alHalaby","age":28,"place":" western Gaza City"},
{"day":12,"count":11,"name":"Mohammad Sweity Abu Askar","age":20,"place":" western Gaza City"},
{"day":12,"count":12,"name":"Khawla alHawajri","age":25,"place":" Nuseirat refugee camp"},
{"day":12,"count":13,"name":"Ola Wishahi","age":31,"place":" Mabarra association for the disabled in Jabalia"},
{"day":12,"count":14,"name":"Suha Abu Saade","age":38,"place":" Mabarra association for the disabled in Jabalia"},
{"day":12,"count":15,"name":"Mohammad Edrees Abu Sweilem","age":20,"place":" Jabalia"},
{"day":12,"count":16,"name":"Rateb Subhi alSaifi","age":22,"place":" Sheikh Radwan – Gaza City"},
{"day":12,"count":17,"name":"Azmi Mahmoud Obeid","age":51,"place":" Sheikh Radwan – Gaza City"},
{"day":12,"count":18,"name":"Nidal Mahmoud Abu alMalsh","age":22,"place":" Sheikh Radwan – Gaza City"},
{"day":12,"count":19,"name":"Suleiman Said Obeid","age":56,"place":" Sheikh Radwan – Gaza City"},
{"day":12,"count":20,"name":"Mustafa Muhammad Inaya","age":58,"place":" Sheikh Radwan – Gaza City"},
{"day":12,"count":21,"name":"Ghassan Ahmad alMasri","age":25,"place":" Sheikh Radwan – Gaza City"},
{"day":12,"count":22,"name":"Rif’at Youssef Amer","age":36,"place":" alSaftawi"},
{"day":12,"count":23,"name":"Rif’at Syouti","age":null,"place":" western Gaza City" },
{"day":12,"count":24,"name":"Nahedh Na’im alBatsh","age":41,"place":" Khan Younis"},
{"day":12,"count":25,"name":"Baha’ Majed alBatsh","age":28,"place":" Khan Younis"},
{"day":12,"count":26,"name":"Qusai Issam alBatsh","age":12,"place":" Khan Younis"},
{"day":12,"count":27,"name":"Aziza Yousef alBatsh","age":59,"place":" Khan Younis"},
{"day":12,"count":28,"name":"Ahmad No’man alBatsh","age":27,"place":" Khan Younis"},
{"day":12,"count":29,"name":"Mohammad Issam alBatsh","age":17,"place":" Khan Younis"},
{"day":12,"count":30,"name":"Yahia ‘Ala’ AlBatsh","age":18,"place":" Khan Younis"},
{"day":12,"count":31,"name":"Jalal Majed alBatsh","age":26,"place":" Khan Younis"},
{"day":12,"count":32,"name":"Mahmoud Majed alBatsh","age":22,"place":" Khan Younis"},
{"day":12,"count":33,"name":"Majed Sobhi alBatsh","age": null,"place":"Khan Younis"},
{"day":12,"count":34,"name":"Marwa Majed alBatsh","age":25,"place":" Khan Younis"},
{"day":12,"count":35,"name":"Khaled Majed alBatsh","age":20,"place":" Khan Younis"},
{"day":12,"count":36,"name":"Ibrahim Majed alBatsh","age":18,"place":" Khan Younis"},
{"day":12,"count":37,"name":"Manar Majed alBatsh","age":13,"place":" Khan Younis"},
{"day":12,"count":38,"name":"Amal Hussein alBatsh","age":49,"place":" Khan Younis"},
{"day":12,"count":39,"name":"Anas Ala’ alBatsh","age":10,"place":" Khan Younis"},
{"day":12,"count":40,"name":"Qusai Ala’ alBatsh","age":20,"place":" Khan Younis"},
{"day":12,"count":41,"name":"Mohannad Yousef Dheir","age":23,"place":" Rafah"},
{"day":12,"count":42,"name":"Shadi Mohammad Zo’rob","age":21,"place":" Rafah"},
{"day":12,"count":43,"name":"Imad Bassam Zo’rob","age":21,"place":" Rafah"},
{"day":12,"count":44,"name":"Mohannad Yousef Dheir","age":23,"place":" Rafah"},
{"day":12,"count":45,"name":"Mohammad Arif","age":13,"place":" eastern Gaza City"},
{"day":12,"count":46,"name":"Mohammad Ghazi ‘Arif","age":35,"place":" eastern Gaza City"},
{"day":12,"count":47,"name":"Ghazi Mustafa Arif","age":62,"place":" eastern Gaza City"},
{"day":12,"count":48,"name":"Ahmad Yousef Dalloul","age":47,"place":" Gaza"},
{"day":12,"count":49,"name":"Fadi Ya’coub Sukkar","age":25,"place":" Gaza"},
{"day":12,"count":50,"name":"Qassem Jaber Odah","age":16,"place":" Khan Younis"},
{"day":12,"count":51,"name":"Mohammad Abdullah Sharatha","age":53,"place":" Jabalia"},
{"day":12,"count":52,"name":"Mohammad Ahmed Basal","age":19,"place":" Gaza City"},
{"day":11,"count":1,"name":"Wisam AbdulRazeq Hasan Ghannam","age":31,"place":" Rafah"},
{"day":11,"count":2,"name":"Mahmoud AbdulRazeq Hasan Ghannam","age":28,"place":" Rafah"},
{"day":11,"count":3,"name":"Kifah Shaker Ghannam","age":33,"place":" Rafah"},
{"day":11,"count":4,"name":"Ghalia Thieb Ghannam","age":57,"place":" Rafah"},
{"day":11,"count":5,"name":"Mohammad Munir ‘Ashour","age":26,"place":" Rafah"},
{"day":11,"count":6,"name":"Nour Marwan anAjdi","age":10,"place":" Rafah"},
{"day":11,"count":7,"name":"Anas Rezeq abu alKas","age":33,"place":" Gaza City doctor"},
{"day":11,"count":8,"name":"Abdullah Mustafa abu Mahrouq","age":22,"place":" Deir alBalah"},
{"day":11,"count":9,"name":"Mahmoud Waloud","age":26,"place":" Jabalia"},
{"day":11,"count":10,"name":"Hazem Ba’lousha","age":null,"place":" Jabalia"},
{"day":11,"count":11,"name":"Ala' Abdul Nabi","age": null,"place":"Beit Lahia"},
{"day":11,"count":12,"name":"Ahmed Zaher Hamdan","age":24,"place":" Beit Hanoun"},
{"day":11,"count":13,"name":"Mohammad Kamel alKahlout","age":25,"place":" Jabalia"},
{"day":11,"count":14,"name":"Sami Adnan Shaldan","age":25,"place":" Gaza City"},
{"day":11,"count":15,"name":"Salem alAshhab","age":40,"place":" Gaza City"},
{"day":11,"count":16,"name":"Raed Hani Abu Hani","age":31,"place":" Rafah"},
{"day":11,"count":17,"name":"Mohammad Rabea Abu Hmeedan","age":65,"place":" Jabalia"},
{"day":11,"count":18,"name":"Shahrman Ismail Abu alKas","age":42,"place":" AlBureij"},
{"day":11,"count":19,"name":"Mazin Mustafa Aslan","age":63,"place":" Al Bureij"},
{"day":11,"count":20,"name":"Mohammad Samiri","age":24,"place":" Deir alBalah"},
{"day":11,"count":21,"name":"Rami Abu Mosa’ed","age":23,"place":" Deir alBalah"},
{"day":11,"count":22,"name":"Saber Sokkar","age":80,"place":" Gaza City"},
{"day":11,"count":23,"name":"Hussein Mohammad alMamlouk","age":47,"place":" Gaza City"},
{"day":11,"count":24,"name":"Nasser Rabah Mohammad Sammama","age":49,"place":" Gaza City"},
{"day":11,"count":25,"name":"AbdulHalim AbdulMo’ty Ashra","age":54,"place":" Deir alBalah"},
{"day":11,"count":26,"name":"Sahar Salman Abu Namous","age":3,"place":" Beit Hanoun"},
{"day":11,"count":27,"name":"Odai Rafiq Sultan","age":27,"place":" Jabalia"},
{"day":11,"count":28,"name":"Jom’a Atiyya Shallouf","age":25,"place":" Rafah"},
{"day":11,"count":29,"name":"Bassam AbulRahman Khattab","age":6,"place":" Deir alBalah"},
{"day":10,"count":1,"name":"Mahmoud Lutfi alHajj","age":58,"place":" Khan Younisfather of six"},
{"day":10,"count":2,"name":"Bassema Abdulfatteh Mohammad alHajj","age":48,"place":" Khan Younismother of six"},
{"day":10,"count":3,"name":"Asma’ Mahmoud alHajj","age":22,"place":" Khan Younis"},
{"day":10,"count":4,"name":"Fatima Mahmoud alHajj","age":12,"place":" Khan Younis"},
{"day":10,"count":5,"name":"Sa’ad Mahmoud alHajj","age":17,"place":" Khan Younis"},
{"day":10,"count":6,"name":"Najla’ Mahmoud alHajj","age":29,"place":" Khan Younis"},
{"day":10,"count":7,"name":"Tareq Mahmoud alHajj","age":18,"place":" Khan Younis"},
{"day":10,"count":8,"name":"Omar Mahmoud alHajj","age":20,"place":" Khan Younis"},
{"day":10,"count":9,"name":"Baha’ Abu alLeil","age":35,"place":" Gaza City"},
{"day":10,"count":10,"name":"Suleiman Saleem Mousa alAstal","age":17,"place":" Khan Younis"},
{"day":10,"count":11,"name":"Ahmed Saleem Mousa alAstal","age":24,"place":" Khan Younis Suleiman’s brother"},
{"day":10,"count":12,"name":"Mousa Mohammed Taher alAstal","age":50,"place":" Khan Younis"},
{"day":10,"count":13,"name":"Ibrahim Khalil Qanan","age":24,"place":" Khan Younis"},
{"day":10,"count":14,"name":"Mohammad Khalil Qanan","age":26,"place":" Khan Younis Ibrahim’s brother"},
{"day":10,"count":15,"name":"Ibrahim Sawali","age":28,"place":" Khan Younis"},
{"day":10,"count":16,"name":"Hamdi Badea’ Sawali","age":33,"place":" Khan Younis"},
{"day":10,"count":17,"name":"Mohammad al‘Aqqad","age":24,"place":" Khan Younis"},
{"day":10,"count":18,"name":"Ismael Hassan Abu Jame’","age":19,"place":" Khan Younis"},
{"day":10,"count":19,"name":"Hussein Odeh Abu Jame’","age":75,"place":" Khan Younis"},
{"day":10,"count":20,"name":"Abdullah Ramadan Abu Ghazal","age":5,"place":" Beit Hanoun"},
{"day":10,"count":21,"name":"Mohammad Ehsan Ferwana","age":27,"place":" Khan Younis"},
{"day":10,"count":22,"name":"Salem Qandil","age":27,"place":" Gaza City"},
{"day":10,"count":23,"name":"Amer alFayyoumi","age":30,"place":" Gaza City"},
{"day":10,"count":24,"name":"Ra’ed azZourah","age":32,"place":" Khan Younis"},
{"day":9,"count":1,"name":"Hamed Shihab","age": null,"place":"Journalist – Gaza"},
{"day":9,"count":2,"name":"Salima al‘Arja","age":53,"place":" Rafah"},
{"day":9,"count":3,"name":"Miriam ‘Atiya al‘Arja","age":9,"place":" Rafah"},
{"day":9,"count":4,"name":"Rafiq alKafarna","age":30,"place":" "},
{"day":9,"count":5,"name":"AbdulNasser Abu Kweik","age":60,"place":" "},
{"day":9,"count":6,"name":"Khaled Abu Kweik","age":31,"place":" "},
{"day":9,"count":7,"name":"Mohammad Mustafa Malika","age":2,"place":" "},
{"day":9,"count":8,"name":"Hana’ Mohammed Fu’ad Malaka","age":28,"place":" "},
{"day":9,"count":9,"name":"Hatem Abu Salem","age":null,"place":" Gaza City"},
{"day":9,"count":10,"name":"Mohammad Khaled anNimra","age":22,"place":" "},
{"day":9,"count":11,"name":"Sahar Hamdan alMasry","age":40,"place":" Beit Hanoun"},
{"day":9,"count":12,"name":"Mohammad Ibrahim alMasry","age":14,"place":" Beit Hanoun"},
{"day":9,"count":13,"name":"Amjad Hamdan","age":23,"place":" Beit Hanoun"},
{"day":9,"count":14,"name":"Hani Saleh Hamad","age":57,"place":" Beit Hanoun"},
{"day":9,"count":15,"name":"Ibrahim Hani Saleh Hamad","age":20,"place":" Beit Hanoun"},
{"day":9,"count":16,"name":"Mohammad Khalaf Nawasra","age":4,"place":" alMaghazi"},
{"day":9,"count":17,"name":"Nidal Khalaf Nawasra","age":5,"place":" alMaghazi"},
{"day":9,"count":18,"name":"Salah Awad Nawasra","age":24,"place":" alMaghazifather of Mohammad and Nidal"},
{"day":9,"count":19,"name":"‘Aesha Najm alNawasra","age":23,"place":" alMaghazi mother of Mohammad and Nidalpregnant in the fourth month"},
{"day":9,"count":20,"name":"Naifa Mohammed Zaher Farajallah","age":80,"place":" alMughraqa"},
{"day":9,"count":21,"name":"Amal Yousef AbdulGhafour","age":20,"place":" Khan Younis"},
{"day":9,"count":22,"name":"Nariman Jouda AbdulGhafour","age":2,"place":" Khan Younis"},
{"day":9,"count":23,"name":"Ibrahim Daoud alBal’aawy","age": null,"place":" "},
{"day":9,"count":24,"name":"AbdulRahman Jamal azZamely","age":null,"place":" "},
{"day":9,"count":25,"name":"Ibrahim Ahmad ‘Abdin","age":42,"place":" Rafah"},
{"day":9,"count":26,"name":"Mustafa Abu Murr","age":20,"place":" Rafah"},
{"day":9,"count":27,"name":"Khaled Abu Murr","age":22,"place":" Rafah"},
{"day":9,"count":28,"name":"Mazin Faraj AlJarba","age": null,"place":" "},
{"day":9,"count":29,"name":"Marwan Eslayyem","age":null,"place":" "},
{"day":9,"count":30,"name":"Ra’ed Mohammed Shalat","age":37,"place":" alNussairat"},
{"day":9,"count":31,"name":"Yasmin Mohammad Matouq","age":4,"place":" Beit Hanoun"},
{"day":8,"count":1,"name":"Mohammad Sha’ban","age":24,"place":" Gaza"},
{"day":8,"count":2,"name":"Amjad Sha’ban","age":30,"place":" Gaza"},
{"day":8,"count":3,"name":"Khader alBasheeleqety","age":45,"place":" Gaza"},
{"day":8,"count":4,"name":"Rashad Yassin","age":27,"place":" Nusseirat"},
{"day":8,"count":5,"name":"Mohammad Ayman ‘Ashour","age":15,"place":" Khan Younis"},
{"day":8,"count":6,"name":"Riyadh Mohammad Kaware’","age":50,"place":" Khan Younis"},
{"day":8,"count":7,"name":"Bakr Mohammad Joudeh","age":50,"place":" Khan Younis"},
{"day":8,"count":8,"name":"Ammar Mohammad Joudeh","age":26,"place":" Khan Younis"},
{"day":8,"count":9,"name":"Hussein Yousef Kaware’","age":13,"place":" Khan Younis"},
{"day":8,"count":10,"name":"Bassem Salem Kaware’","age":10,"place":" Khan Younis"},
{"day":8,"count":11,"name":"Mohammad Ibrahim Kaware’","age":50,"place":" Khan Younis"},
{"day":8,"count":12,"name":"Mohammad Habib","age":22,"place":" Gaza"},
{"day":8,"count":13,"name":"Ahmed Mousa Habib","age":16,"place":" Gaza"},
{"day":8,"count":14,"name":"Saqr ‘Aayesh al‘Ajjoury","age":22,"place":" Jabalia"},
{"day":8,"count":15,"name":"Ahmad Nael Mahdi","age":16,"place":" Gaza"},
{"day":8,"count":16,"name":"Hafeth Mohammad Hamad","age":26,"place":" Beit Hanoun"},
{"day":8,"count":17,"name":"Ibrahim Mohammad Hamad","age":26,"place":" Beit Hanoun"},
{"day":8,"count":18,"name":"Mahdi Mohammad Hamad","age":46,"place":" Beit Hanoun"},
{"day":8,"count":19,"name":"Fawziyya Khalil Hamad","age":62,"place":" Beit Hanoun"},
{"day":8,"count":20,"name":"Donia Mahdi Hamad","age":16,"place":" Beit Hanoun"},
{"day":8,"count":21,"name":"Soha Hamad","age":25,"place":" Beit Hanoun"},
{"day":8,"count":22,"name":"Suleiman Salam Abu Sawaween","age":22,"place":" Khan Younis"},
{"day":8,"count":23,"name":"Siraj Eyad Abdul‘Aal","age":8,"place":" Khan Younis"},
{"day":8,"count":24,"name":"AbdulHadi Soufi","age":24,"place":" Rafah"}
];

